### ISSUE TITLE
 Installation Documentation

### ISSUE THREAD

**Issue by inosjarv** [sminez/penrose#102]
Hi,
This wm is great!
Can you please make a proper installation documentation.
Thanks in advance!

**Comment by sminez** [comment]
~~This is my personal config provided as reference. I wouldn't really call it a bug to not have documentation...~~

~~Please see the main Penrose library for details of how to use Penrose itself.~~ 

Ah, sorry! Doing this from my phone and didn't see you'd opened this in both repos :facepalm:


As it says in the README: I am in the middle of updating the internal APIs for a 0.2.0 release, improved documentation will be included as part of that. Until the ongoing work is complete, there isn't much point in documenting the way things currently stand.

If you are using the latest release from crates.io, then following one of the examples in the **examples** directory should get you started. I build the binary in release mode and then run it in my .xinitrc, simply calling **startx** from a TTY following login. It _should_ be possible to set up using a display manager as well if you prefer but I haven't tried myself.

This advice from a previous issue is a good place to start: https://github.com/sminez/penrose/issues/84#issuecomment-748413004

**Comment by inosjarv** [comment]
I tried that earlier, but there is no binary generated in target/release folder.
That's why I raised issue.

But if there is stable release coming up, I can wait for that.
Thank you :+1:

**Comment by sminez** [comment]
Penrose is a library not a binary, you will need to write your own main.rs and compile that. Alternatively, you can compile one of the examples using `cargo build --example=<example name>`

This will place the resulting binary in `target/debug/examples/<example name>`

**Comment by inosjarv** [comment]
aah, okay! Thank you again!
