### ISSUE TITLE
Are you interested in an x11rb port/backend?

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#104]
### Is your feature request related to a problem? Please describe

The problem might be "too much time". I am not sure. There is no problem?

### Describe the change / addition you'd like to see made

I'd like to try to add an x11rb "backend" in addition to the current rust-xcb one and submit it as a PR. Before doing that, I want to give you a chance to say "you are wasting your time, that will never work / will never be accepted".

### Describe alternatives you've considered

Uhm... going for a walk?

### Additional context

Dunno what you might want here. Uhm. I'm the author of x11rb, did some libxcb releases (the C library) and also work on libcairo (the C library). Is that the kind of context you are interested here?

Edit: Actually, this might server as an experiment on what your `XConn` trait is capable of and what it cannot be used for.

**Comment by sminez** [comment]
If you're willing to put in the work I'd love to have it! Probably best to put it in a top level module in the way I've done so far for **xcb** if that's alright?

Let me know if you have any questions: XConn isn't as well documented as the rest of **core** currently so things might be a little unclear in places :pensive:

**Comment by psychon** [comment]
Okay, thanks. Seems like I have a project for the weekend(s). :-)
