### ISSUE TITLE
Could not resolve keysym XF86FullScreen

### ISSUE THREAD

**Issue by pepsi** [sminez/penrose#11]
Im trying to run this on Alpine 3.12 x86_64 musl.
Host is a ThinkPad T410, 4gb ram, quad core 2.4ghz cpu.
When trying to run this with startx, I get the following error
The XKEYBOARD keymap compiler reports:
> Internal error: Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
xinit: connection to X server lost.

Im running on nightly rust, using the config in the example dir.
Also pulling the latest penrose from the git repo, rather than the crates.io, since thats outdated.
If you want any more information ill be happy to leave it here :)

**Comment by sminez** [comment]
Oh ok, interesting. That sounds like an error from xmodmap rather than Penrose itself i think...

Can you share the output of what you get when running 'xmodmap -pke' ?

**Comment by pepsi** [comment]
https://clbin.com/PjNXs
Its a long output so ill put it on a paste site rather than posting here.
I had to run this command while dwm is running, else I would get a screen not found error.

**Comment by sminez** [comment]
Ok, looking at your `xmodmap` output, that keysym _is_ missing. That said, it's not in mine either and nothing in the example config uses it...

is your xinitrc just `exec <path/to/penrose/binary>` ?

You will need to remove the attempt to spawn the startup script I suspect unless you have created one at that path. TBH, I need to set up a cleaner example config. I'll get on that soon 👍

**Comment by sminez** [comment]
Looking at the error you give in particular, it may not be penrose specific:
https://forums.freebsd.org/threads/error-when-starting-the-x-server.75038/
https://bugs.archlinux.org/task/65730
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953032
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245384

**Comment by sminez** [comment]
@pepsi have you been able to get to the bottom of this? I'm not able to reproduce this currently with the information you have provided.

**Comment by pepsi** [comment]
I have not, but it seems to be some sort of a missing/outdated package. You may close this issue, since it's not a problem with Penrose.
