### ISSUE TITLE
The code is casting/interpreting a DestroyNotifyEvent to/as MapNotifyEvent

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#111]
### Describe the bug

You are casting a DestroyNotifyEvent event to MapNotifyEvent:

https://github.com/sminez/penrose/blob/69912708f7982b7d6a61b9fa549040fb4c3625fb/src/xcb/api.rs#L301-L302

### To Reproduce

Uhm... sorry, this is not a crash. There is nothing to reproduce.

### Versions & OS Details

Sorry, I pass. The above has a permalink to the code in question.

### Additional context

- [ ] minimal main.rs that reproduces the issue
- [ ] debug log output
- [ ] output of running `xmodmap -pke` (for keybinding issues)
- Both `DestroyNotifyEvent` and `MapNotifyEvent` begin with the same layout:
  - (The usual boilerplate like response type and sequence number)
  - They both have one byte of padding
  - Then come two window fields
  - Thus, this mix-up actually has no noticable effect and everything still works fine (the events also have the same on-the-wire-size, so there is no memory unsafety here). Still, it feels like a problem to me, hence this report.

**Comment by sminez** [comment]
Urgh, that's gross...not sure how I've managed that :disappointed: fix being pushed now.
