### ISSUE TITLE
Argument of XConn::atom_prop() should be Atom or the xcb implementation be changed

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#112]
[Sorry, but this time I will completely ignore the issue template; feel free to tell me not to do that again]

Let's look at this code: https://github.com/sminez/penrose/blob/69912708f7982b7d6a61b9fa549040fb4c3625fb/src/xcb/xconn.rs#L330-L331
This uses `Atom::from_str(name)?` on the argument. Thus, this will always fail with non-`Atom` arguments. That's unexpected and feels like a bug to me. I wanted to just fix this, but since this function doesn't seem to have any callers, I decided to report this as an issue instead.

Options that I see:
- Just remove this function (but it exists so that people can use it from their config, I guess)
- Change the argument type from `&str` to `Atom`
- Change the implementation to work similarly to `get_str_prop()` so that it supports arbitrary atom names

**Comment by sminez** [comment]
Changing to allow arbitrary strings rather than internally expecting an Atom sounds like the right way to do it. You're right that it's there so that end users can get at it but also in case WindowManager (or hooks / extensions) needs to get at individual props as well.
