### ISSUE TITLE
MotionNotifyEvent::detail does not contain information about a button

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#113]
The code here treats the detail field of `ButtonPressEvent`, `ButtonReleaseEvent`, and `MotionNotifyEvent` the same: https://github.com/sminez/penrose/blob/0921c92f3c88af8c9a90149e051b4dd0f255e1c5/src/xcb/conversions.rs#L115-L157

[Here are the relevant docs](https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#events:ButtonPress). According to this, the `detail` in the button events is a `BUTTON` while for `MotionNotify` it is something about event compression:

> If PointerMotionHint is selected, the server is free to send only one MotionNotify event (with detail Hint) to the client for the event window until [...]

Found because my x11rb code fails to compile due to a type error:

> expected `u8`, found struct `x11rb::protocol::xproto::Motion`

**Comment by sminez** [comment]
This is the conversion code for the `xcb` backend...why is it running with your x11rb code?

**Comment by psychon** [comment]
Sorry for the confusion. I am writing the implementation for x11rb and for that I look at how the xcb backend works and try to do things similarly. Thus, I more or less copied the code from the xcb backend, tried to make it work with x11rb, but the compiler told me that the types don't match. After a closer look, I concluded that the code in the xcb backend is wrong.

**Comment by psychon** [comment]
Perhaps an example helps:
- `MotionNotifyEvent::detail` only ever contains the values 0 or 1. These are `xcb::xproto::MOTION_NORMAL` or `xcb::xproto::MOTION_HINT`.
- For `ButtonPressEvent` and `ButtonReleaseEvent`, `detail` contains the number of the button that was pressed. The relevant defines are `xcb::xproto::BUTTON_INDEX_1` to `BUTTON_INDEX_5` (but those have type `u32` and not `u8`, so I might be wrong about these defines being relevant)

**Comment by sminez** [comment]
Ah ok, thanks. The mouse support in Penrose is minimal to put it mildly. There are open issues to fully implement mouse actions other than just click == run function with no args.

If you think the xconn trait itself (or XEvent types) needs modifying to sort this then that is something we should do :+1:

**Comment by sminez** [comment]
Fixed in #300
