### ISSUE TITLE
Should check the server's RandR version

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#115]
The current code checks if the RandR extension is available...
https://github.com/sminez/penrose/blob/0921c92f3c88af8c9a90149e051b4dd0f255e1c5/src/xcb/api.rs#L127-L131
before using it:
https://github.com/sminez/penrose/blob/0921c92f3c88af8c9a90149e051b4dd0f255e1c5/src/xcb/api.rs#L577

However, the `GetScreenResources` request was only added in RandR 1.2. Earlier versions do not have it.

Thus, the code really should use `xcb::randr::query_version` to check whether the server supports at least RandR 1.2.

(How does one know which version is required for which request? I don't really know. I checked xcb-proto's XML description. It has a line saying `<!-- new in version 1.2 -->` and I think everything afterwards requires RandR 1.2 or better.)

(What happens with older X11 servers? I'm not quire sure. I guess a panic, because the X11 server answers `GetScreenResources` with bad requests and this error is turned into a panic in `penrose::xcb::xconn::XcbConnection::current_outputs()`.)

**Comment by sminez** [comment]
I think that a panic is probably the only thing we can do in this case? That said, a quick google shows that RandR 1.2 was released in 2007 and 1.3 was released in 2008...I'm not conviced that `penrose` is going to be run (or be runnable at all) on anything that is running 1.2 :shrug:

**Comment by psychon** [comment]
Yeah, okay. Feel free to close this. Alternatively, this issue might be retitled "error message could be clearer for that case" since "bad request" is not all that self-explanatory.

I guess I was just confused that the code explicitly checks whether RandR is supported at all and then returns a nice `Err`, but does not check the necessary version.

**Comment by sminez** [comment]
Yeah a better error would definitely be good :+1:
Just saying I'm not sure if we'll hit that case in practice or not! Keep the issue open and I'll get that sorted out

**Comment by sminez** [comment]
Implemented in #118

**Comment by psychon** [comment]
Thanks!
