### ISSUE TITLE
I doubt a lot that penrose::xcb::draw::XcbDraw::temp_context() works

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#119]
Hi,

I just looked at your `Draw` trait and wondered how `temp_context()` is implemented. Well...
The implementation generates a new XID:
https://github.com/sminez/penrose/blob/f319732fbe972d0397c3870e0aad19492c4bf843/src/xcb/draw.rs#L120
and then just gives that XID to cairo:
https://github.com/sminez/penrose/blob/f319732fbe972d0397c3870e0aad19492c4bf843/src/xcb/draw.rs#L130
Nothing actually creates a Pixmap or Window for that XID. That's not going to fly, I fear (but I am too lazy to try it out right now; feel free to tell me I should actually try this).

I do not know what the use for `temp_context()` is. This just allows me to draw to something that will not be visible. Why would it do that? If you could explain that, I might have some suggestions on what to do (a random idea would be to create cairo xcb surface for the root window and then using `create_similar()` to get another surface. This makes cairo internally create a Pixmap for that second xcb surface.)

**Comment by sminez** [comment]
The intension was to give a way for determining the extent of text based widgets without needing to actually map a window to the screen. It's part of an experiment I was tinkering with to re-implement dmenu using `Draw` as a back end (`crates/pmenu` if you are interested).

It _kind of_ works...but there are some really odd bugs with it at the moment: I haven't played around with the Cairo APIs that much beyond what is in place for the status bar which is pretty basic. I wouldn't be surprised if it's just straight up broken as you say. Any advice you can give around that would be appreciated!

**Comment by psychon** [comment]
Completely untested, but I would expect this to work fine:
```diff
diff --git a/src/xcb/draw.rs b/src/xcb/draw.rs
index c45da0f..e771cec 100644
--- a/src/xcb/draw.rs
+++ b/src/xcb/draw.rs
@@ -117,7 +117,6 @@ impl Draw for XcbDraw {
     }
 
     fn temp_context(&self, w: u32, h: u32) -> Result<Self::Ctx> {
-        let id = self.api.conn().generate_id();
         let xcb_screen = self.api.screen(0)?;
         let depth = self.api.get_depth(&xcb_screen)?;
         let mut visualtype = self.api.get_visual_type(&depth)?;
@@ -127,7 +126,7 @@ impl Draw for XcbDraw {
 
             cairo::XCBSurface::create(
                 &cairo::XCBConnection::from_raw_none(conn_ptr),
-                &cairo::XCBDrawable(id),
+                &cairo::XCBDrawable(self.api.root()),
                 &cairo::XCBVisualType::from_raw_none(
                     &mut visualtype.base as *mut xcb::ffi::xcb_visualtype_t
                         as *mut cairo_sys::xcb_visualtype_t,
@@ -137,7 +136,7 @@ impl Draw for XcbDraw {
             )?
         };
 
-        surface.set_size(w as i32, h as i32)?;
+        let surface = surface.create_similar(cairo::Content::Color, w as i32, h as i32)?;
         let ctx = cairo::Context::new(&surface);
 
```
This is the `create_similar()` approach I mentioned above: It creates a cairo surface for the root window and then uses that to call `create_similar()` to create a Pixmap (that is owned by cairo).

**Comment by sminez** [comment]
Ah ok, interesting. I'll give it a shot!

**Comment by sminez** [comment]
Looks like that all works fine @psychon :+1:
