### ISSUE TITLE
Tiny workspace after changing monitors

### ISSUE THREAD

**Issue by rivertam** [sminez/penrose#12]
## Context

My greeter (I assume) (gdm3) detects all my monitors, but I really only want to use my 4k external monitor.

## What happens

When I just start, what I get is all the windows take up all the space on both screens (mirrored screens), but it looks low resolution on the 4k monitor.

The way I normally switch monitors on i3 is:

```
xrandr --output eDP-1 --off
xrandr --output DP-3 --mode 3840x2160
```

Using the penrose example, this results in a really low resolution workspace in the top left of my 4k, and I can't figure out how I'd resize it.

**Comment by rivertam** [comment]
Cool library btw. :+1:

**Comment by sminez** [comment]
Ah, I think I know what this will be. Currently Penrose only detects screen resolution on init, I saw that any xrandr changes once Penrose was running are currently not picked up :disappointed: (this is why I mentioned hooking into xrandr events in the video update). As a result, Penrose is going to treat your 4k as having the resolution of your internal display as it is now the first monitor it knows about...
I suspect this will require a new hook or possibly auto detecting when screens are updated through xrandr and dropping the current set of screens and replacing it with the newly detected ones.

**Comment by sminez** [comment]
Hi @rivertam , I've just pushed an update that makes penrose automatically re-detect attached screens when `xrandr` is run. It's working for me when I plug into an external monitor or my TV over HDMI but it would be good to see if it resolves this issue for you. You can update your cargo toml to point at the  current head of `develop` like [this](https://github.com/sminez/my-penrose-config/blob/master/Cargo.toml#L10). If you enable debug logging you should see when the hook is being fired and what penrose thinks the current screen dimensions are :+1:

**Comment by rivertam** [comment]
Nice, I'll try to check it out this week if I get the chance.

**Comment by sminez** [comment]
Hi @rivertam, have you had a chance to try this out yet?

**Comment by sminez** [comment]
Closing for now. Pleaes open again if this issue shows up again

**Comment by rivertam** [comment]
Did manage to try, and it works. :) Thanks!
