### ISSUE TITLE
Something wrong with RandR event handling: Ignoring the event base

### ISSUE THREAD

**Issue by psychon** [sminez/penrose#124]
Here, RandR events are handled specially; that looks okay:
https://github.com/sminez/penrose/blob/1092fcb08325a622ef14605155e76d805b1e6f04/src/xcb/api.rs#L266-L268
However, this one seems incorrect since the event base is not applied:
https://github.com/sminez/penrose/blob/1092fcb08325a622ef14605155e76d805b1e6f04/src/xcb/api.rs#L321

**Comment by sminez** [comment]
From what I could tell, this was a quirk with the rust-xcb crate: I only needed to check it for randr notify. I might be wrong on that of course but screen change events _do_ fire so it is getting picked up :shrug:
