### ISSUE TITLE
XConn should handle common properties correctly

### ISSUE THREAD

**Issue by sminez** [sminez/penrose#125]
Currently the `XConn` trait can only really support pulling string and atom properties which means that `WM_HINTS` and `WM_NORMAL_HINTS` are kind of unaccessible. I hacked the following together for the `xcb` based back end and it lets me get at the raw bytes which will then need parsing:

```rust
fn main() {
    let (conn, _) = xcb::Connection::connect(None).unwrap();

    let intern = |name| {
        xcb::intern_atom(&conn, false, name)
            .get_reply()
            .unwrap()
            .atom()
    };

    let show_prop = |id, name| {
        let r = xcb::get_property(&conn, false, id, intern(name), xcb::ATOM_ANY, 0, 1024)
            .get_reply()
            .unwrap();

        match r.format() {
            32 => println!("{}: &[u32]={:?}", name, r.value::<u32>()),
            16 => println!("{}: &[u16]={:?}", name, r.value::<u16>()),
            8 => println!("{}: &[u8]={:?}", name, r.value::<u8>()),
            _ => unimplemented!(),
        }
    };

    show_prop(0x260002d, "WM_NORMAL_HINTS");
    show_prop(0x260002d, "WM_HINTS");
    show_prop(0x260002d, "WM_NAME");
}
```

This is probably going to result in `XConn` having a single `get_property` method that takes an enum arg specifying the type of prop and returns an enum of the possible return types.

**Comment by psychon** [comment]
In case you do not want to write your own parsing code, but use some else's, there is a crate for that: https://docs.rs/xcb-util/0.3.0/xcb_util/icccm/struct.WmHints.html
Adding a special case to get the `input` bit from `WM_HINTS` would be kind of ugly, but still possible.

**Comment by sminez** [comment]
I've got something written up locally but haven't pushed it yet: just trying to neaten up the top level API a bit. Should hopefully have it ready fairly soon, I've got distracted by going through the ICCCM and EWMH specs again and seeing what more I can get working :sweat_smile:

**Comment by sminez** [comment]
I've raised #126 with the initial work on this: at the moment I'm only worrying about parsing details from things like `WmHints` and `WmNormalHints` that are actually going to affect penrose. This just adds the methods to `XConn` but doesn't make full use of them yet.
