### ISSUE TITLE
Keybindings issue

### ISSUE THREAD

**Issue by Catvert** [sminez/penrose#13]
Hey,
I have a strange issue with the keybindings. I have tried to run your personal config(my-penrose-config) and the M-j, M-k, the keys for workspaces... are not working properly. For example, the M-j key, normally assigned to cycle clients forward, is assigned in my build to cycling screen(or something similar) and I have tried to remap it to M-t and the M-t is cycling forward correctly(but M-j keeps doing the cycle_screen even though I don't have anything binded on it anymore).
I have also tried to map the M-d shortcut to rofi but the mapping is not working(but with M-r for example, no problem).

It's quite hard to describe and my English is not perfect so if you want more precision and informations feel free to ask me.

Here is an example of my config : 
```rust
/**
 * My personal penrose config (build from the head of develop)
 */
#[macro_use]
extern crate penrose;

use penrose::helpers::spawn;
use penrose::hooks::LayoutHook;
use penrose::layout::{bottom_stack, paper, side_stack};
use penrose::{
    Backward, Config, Forward, Layout, LayoutConf, Less, More, WindowManager, XcbConnection,
};
use simplelog::{LevelFilter, SimpleLogger};
use std::env;
use std::process::Command;

fn main() {
    SimpleLogger::init(LevelFilter::Info, simplelog::Config::default()).unwrap();

    let mut config = Config::default();
    config.workspaces = &["1", "2", "3", "4", "5", "6", "7", "8", "9"];
    config.fonts = &["Fira Code:size=10", "Iosevka Nerd Font:size=10"];
    config.floating_classes = &["rofi", "dmenu", "dunst", "polybar", "pinentry-gtk-2"];

    let follow_focus_conf = LayoutConf {
        floating: false,
        gapless: true,
        follow_focus: true,
    };
    let n_main = 1;
    let ratio = 0.6;
    config.layouts = vec![
        Layout::new("[side]", LayoutConf::default(), side_stack, n_main, ratio),
        Layout::new("[botm]", LayoutConf::default(), bottom_stack, n_main, ratio),
        Layout::new("[papr]", follow_focus_conf, paper, n_main, ratio),
        Layout::floating("[----]"),
    ];

    let script_path = |script| format!("{}/.config/scripts/{}", env::var("HOME").unwrap(), script);
    let power_script = script_path("power-menu.sh");

    let power_menu = Box::new(move |wm: &mut WindowManager| {
        match Command::new(&power_script).output() {
            Ok(choice) => {
                match String::from_utf8(choice.stdout).unwrap().as_str() {
                    "restart-wm\n" => wm.exit(),
                    _ => (), // other options are handled by the script
                }
            }
            Err(_) => return, // user exited without making a choice
        };
    });

    let key_bindings = gen_keybindings! {
        // Program launch
        //"M-d" => run_external!("rofi -show drun"),
        "M-r" => run_external!("/home/finch/.config/scripts/rofi-apps"),
        //"M-d" => run_external!("rofi -show drun"),
        "M-Return" => run_external!("kitty"),

        // actions
        "M-A-s" => run_external!("screenshot"),
        "M-A-k" => run_external!("toggle-kb-for-tada"),
        "M-A-l" => run_external!("lock-screen"),
        "M-A-m" => run_external!("xrandr --output HDMI-1 --auto --right-of eDP-1 "),

        // client management
        "M-t" => run_internal!(cycle_client, Forward), // With M-t, it's working ! But pressing M-j still do the cycle_screen even though this key is not bind in this config file.
        "M-k" => run_internal!(cycle_client, Backward), // cycle_screen ? 
        "M-S-j" => run_internal!(drag_client, Forward), // Same
        "M-S-k" => run_internal!(drag_client, Backward), // Same
        "M-q" => run_internal!(kill_client),

        // workspace management
        "M-Tab" => run_internal!(toggle_workspace),
        "M-bracketright" => run_internal!(cycle_screen, Forward),
        "M-bracketleft" => run_internal!(cycle_screen, Backward),
        "M-S-bracketright" => run_internal!(drag_workspace, Forward),
        "M-S-bracketleft" => run_internal!(drag_workspace, Backward),

        // Layout & window management
        "M-grave" => run_internal!(cycle_layout, Forward),
        "M-S-grave" => run_internal!(cycle_layout, Backward),
        "M-A-Up" => run_internal!(update_max_main, More),
        "M-A-Down" => run_internal!(update_max_main, Less),
        "M-A-Right" => run_internal!(update_main_ratio, More),
        "M-A-Left" => run_internal!(update_main_ratio, Less),
        "M-A-C-Escape" => run_internal!(exit),
        "M-A-Escape" => power_menu;

        forall_workspaces: config.workspaces => { // Not working at all
            "M-{}" => focus_workspace,
            "M-S-{}" => client_to_workspace,
        }
    };

    // Set the root X window name to be the active layout symbol so it can be picked up by polybar
    let active_layout_as_root_name: LayoutHook = |wm: &mut WindowManager, _, _| {
        wm.set_root_window_name(wm.current_layout_symbol());
    };
    config.layout_hooks.push(active_layout_as_root_name);

    let conn = XcbConnection::new();
    let mut wm = WindowManager::init(config, &conn);

    spawn(script_path("penrose-startup.sh"));
    active_layout_as_root_name(&mut wm, 0, 0);
    wm.grab_keys_and_run(key_bindings);
}
```

**Comment by sminez** [comment]
Hi @Catvert, it would be really helpful if you can provide a minimal failing example config for this one (e.g. ability to spawn a terminal and the attempted keybindings that are not working). I suspect there may be a couple of things going on: importantly, can you try running with `debug` logging enabled and share the startup output? That should include the raw key codes that are being mapped by the `gen_keybindings` macro. If you can also provide the output of running `xmodmap -pke` that would be really helpful as that is what the macro is using to generate the bindings.

I suspect your modifier is altered in some way if the `forall_workspaces` bindings are failing but that wouldn't explain why `M-j` is still bound... :confused:

**Comment by Catvert** [comment]
Hey,
Here is more minimal config that reproduce the same weird behaviors : 
```rust
#[macro_use]
extern crate penrose;

use penrose::{Backward, Config, Forward, Less, More, WindowManager, XcbConnection};
use simplelog::{LevelFilter, SimpleLogger};

fn main() {
    SimpleLogger::init(LevelFilter::Debug, simplelog::Config::default()).unwrap();
    let config = Config::default();
    let key_bindings = gen_keybindings! {
        "M-semicolon" => run_external!("firefox"), // Working
        "M-Return" => run_external!("kitty"), // Working
        "M-t" => run_internal!(cycle_client, Forward), // Working !
        "M-j" => run_internal!(cycle_client, Forward), // cycle_screen forward?
        "M-k" => run_internal!(cycle_client, Backward), // cycle_screen backward?
        "M-S-j" => run_internal!(drag_client, Forward), // drag to other workspace ? Weird behavior
        "M-S-k" => run_internal!(drag_client, Backward), // drag to other workspace ? Weird behavior
        "M-S-q" => run_internal!(kill_client), // Working
        "M-Tab" => run_internal!(toggle_workspace), // Not tested
        "M-bracketright" => run_internal!(cycle_screen, Forward), // Not tested
        "M-bracketleft" => run_internal!(cycle_screen, Backward), // Not tested
        "M-S-bracketright" => run_internal!(drag_workspace, Forward),
        "M-S-bracketleft" => run_internal!(drag_workspace, Backward),
        "M-grave" => run_internal!(cycle_layout, Forward), // Working
        "M-S-grave" => run_internal!(cycle_layout, Backward), // Working
        "M-A-Up" => run_internal!(update_max_main, More), // Working
        "M-A-Down" => run_internal!(update_max_main, Less), // Working
        "M-A-Right" => run_internal!(update_main_ratio, More), // Working
        "M-A-Left" => run_internal!(update_main_ratio, Less), // Working
        "M-A-Escape" => run_internal!(exit); // Working

        forall_workspaces: config.workspaces => { // Not working
            "M-{}" => focus_workspace,
            "M-S-{}" => client_to_workspace,
        }
    };

    let conn = XcbConnection::new();
    let mut wm = WindowManager::init(config, &conn);
    wm.grab_keys_and_run(key_bindings);
}
```
Here is my prev-penrose.log with debug logging and this config : https://pastebin.com/MP7fct8W ; I have pressed some keybinds like M-j, M-k, M-t... to give you as much information as possible in the logs.
Here is the xmodmap -pke : https://pastebin.com/NnhSagpZ

Btw, I have tried to remove all keybinds except the M-j, M-k and forall_worspaces and I've got the same bug.
I have 3 monitors setup with two in mirrors but I have also tried with only 1 monitor connected and it doesn't seem to matter for this bug.

Thanks for your help !

**Comment by Catvert** [comment]
Oh, I just noticed that the problem is with my custom keyboard layout(a custom xkb file). Just tried with the us layout and it's working (I tried yesterday with setxkbmap while running penrose but it didn't worked). It remains an annoying bug, my xmonad/bspwm build don't have this problem.
Here is my XKB File : https://pastebin.com/buZ5RSct

**Comment by sminez** [comment]
Ah! Yeah that'll be it then: penrose parses keybindings once at startup and then doesn't currently listen to any further key mapping changes. When are you running `setxkbmap`? If you do it inside of `main.rs` before using `gen_key_bindings` does that make a difference? I suspect the underlying cause is that the macro is calling `xmodmap -pke` *then* before your keymap has been applied, meaning that once it does get applied some of the keycodes are now wrong.

I'd like to raise a new issue for listening for new key mappings but I'll need to work out how other WMs handle this wrt key mappings that are already defined as `penrose` currently treats your keybindings as immutable which would have to change.

**Comment by Catvert** [comment]
I have tested some cases.
First, If I have my layout active on boot (via /etc/X11/xorg.conf.d/00-keyboard.conf), I have the issue.

Second, If I set my 00-keyboard.conf to fr or us layout, it work. I can then set my custom layout with(before or after the gen_key_bindings, it doesn't matter) :   
```rust
 spawn(format!(
        "xkbcomp -w9 /home/finch/Documents/finch-layout/dist/finch-la.xkb {}",
        env::var("DISPLAY").unwrap()
));
``` 
(btw I tried the Belgium layout and penrose crashed with an invalid keybind M-grave),

Third, the 00-keyboard.conf is set to us and then I applied my layout in the ~/.xprofile config => same issue(I assume that my layout is loaded before penrose and so the problem reappears).

So if I understand correctly, as long as penrose is loaded with a 'standard' layout, the problem disappears. I'm sorry to bother you with this very specific problem. Thanks again!

**Comment by sminez** [comment]
No need to appologise: penrose should be able to handle whatever key layout you want/need to use :slightly_smiling_face: 

The crash from the Belguim layout is odd...I suspect I need better error messaging around what caused the error in order to dig further into that one. I'll look into what Xmonad and dwm do to handle this but I'll need to get my head around it all first I suspect!

**Comment by Catvert** [comment]
Yeah, I think it's 'normal' that penrose crash with the BE layout because I just noticed there's no grave-key on this layout.
Feel free to ask me if you need any more informations.

**Comment by sminez** [comment]
Thanks, I think might need a hand with this one as I'm not overly familiar with non us/gb layouts *or* custom keymaps beyond remapping modifiers. The `gen_keybindings` macro most likely needs its name changing to make it clear that it uses `xmodmap` and all of the edge cases that that brings. As it says in the documentation, you can construct the keybindings yourself by specifying the specific modifier masks and key codes (which is more than a little bit painful!) but it should be possible to come up with an alternate macro that respects the changes you have made via `setxkbmap`.

**Comment by sminez** [comment]
@Catvert I'm afraid there isn't much I can do with this one without more input around how custom keymaps should be handled. Feel free to re-open the issue if you have time to help looking into this.
