### ISSUE TITLE
Example config doesn't compile

### ISSUE THREAD

**Issue by lvx-tenebris** [sminez/penrose#137]
The example config has been updated 7 days ago, but unexpectedly doesn't work. There are 3 main errors, and one with xcb.
in line 172, "map : { "1", "2", "3", "4", "5", "6", "7", "8", "9" } to index_selectors(9)" there is an error, expected type, found '{'.

There is also an error in line 59(and similar), there is a type mismatch, expected u32, found &str in "#cc241d"  [E0308]

in the config builder, line 54, the '?' operator can only be applied to values that implement 'Try'   [E0277]

Is there anything I can do to fix this? I have yet to learn rust, as I am learning how to program with C, and as such i don't understand the documentation entirely to do a fix, and i think it would increase the adoption of the project if we had a functional base config to help us out, new users :D.
Thanks for the attention.
Edit: I am aware git is ahead of release, however, i still don't know what to to.
Also, the .io page is having some problems, the html for the example config isn't rendering, the text is just an html snippet.

**Comment by sminez** [comment]
The example config on develop will only work with develop, not the latest release on crates.io I'm afraid.

I'm surprised to hear it has those errors though if this _is_ compiling against develop: it should be getting checked in the build :confused:

I'll take a look! 

Can you let me know what your cargo.toml looks like please? I'm assuming your using the example verbatim so that's the only other factor really

**Comment by lvx-tenebris** [comment]
Well, I am using the crates.io version, so i really had it comming. My .toml file just really consists on what you have provided on your github.io page, using simple logger and your library. Probably should look more into the documentation. 

Also: https://sminez.github.io/projects/penrose/getting-started/ is having a rendering problem. half of the config is just an HTML snippet, thought i should let you know. 

Anyway: if i want to use the develop branch, I assume i just have to list the git repo as a dependency, correct?

Thanks in advance.

**Comment by sminez** [comment]
If you look at the docs on docs.rs (link is found on the Penrose crates.io page) it will have an example config for that published version.

Develop is not stable and not recommended (or supported) for day to day use

**Comment by lvx-tenebris** [comment]
Well I've got it running now! Now just gotta have some fun with Elkowar's Wacky Widgets and enjoy Rust (and Xml) supremacy. Thanks!

**Comment by lvx-tenebris** [comment]
Well I've got it running now! Now just gotta have some fun with Elkowar's Wacky Widgets and enjoy Rust (and Xml) supremacy. Thanks!
