### ISSUE TITLE
wmctrl tool isn't working on Wm even though Xcb supports the standard

### ISSUE THREAD

**Issue by lvx-tenebris** [sminez/penrose#139]
i am not exactly sure this is a bug, as it will probably end as a feature request, but:

wmctrl is a tool that controls EWMH supporting wms. I am not sure penrose supports ewmh, however, looking through the source code, on the xcb folder, apparently xcb should be compliant, and it does produce output when it says it is managing workspaces (wmctrl -l), however, the function of moving to workspaces (wmctrl -s WORKSPACE) doesn't make any difference to the window manager's state. I am pretty sure it is a bug, as xcb is compliant.

Also, if it isn't compliant, is there any way of piping in information to the window manager from another source, such as the detecting keybinds without actually pressing keys?

penrose=0.2.0
OS: Arch Linux
commands/tools: "wmctrl -l" => Should identify windows and workspaces, and does 
"wmctrl -s 1" => Should move focus from workspace 1 to 2, but doesn't

**Comment by sminez** [comment]
Penrose is very definitely _not_ fully EWMH compliant yet.

XCB itself can be used to make compliant window managers, but that's not the same thing as the penrose::xcb module being EWMH compliant I'm afraid.

As for passing additional information to the window manager from external sources? Out of the box, no. But that's the point of Penrose being a library: if that's something you want then you should be able to build that on top of Penrose :+1:

Penrose itself however, explicitly does not provide functionality like that at the core level.
