### ISSUE TITLE
Rotate clients doesn't update the position of the clients

### ISSUE THREAD

**Issue by augusto-mantilla** [sminez/penrose#145]
### Describe the bug

Using the method [rotate_clients](https://docs.rs/penrose/0.2.0/penrose/core/manager/struct.WindowManager.html#method.rotate_clients) does not update the window's positions in the workspace immediately, but only after changing focus. 

### To Reproduce

1. Execute the keybinding associated to the command rotate_clients, in my case "M-m" => run_internal!(rotate_clients, Backward);
2. Press the keybinding
3. Observe

### Expected behavior

The clients in the workspace should change immediately when the key combination is pressed.

### Screenshots

I thought a [video](https://www.youtube.com/watch?v=tqFsX467bQM) was more relevant

### Versions & OS Details

- OS: Linux
- Arch
- Penrose Version 0.2

### Additional context

- [X] minimal main.rs that reproduces the issue
/**
 * penrose :: minimal configuration
 * This file will give you a functional if incredibly minimal window manager that has multiple
 * workspaces and simple client/workspace movement. For a more fleshed out example see the
 * 'simple_config_with_hooks' example.
 */
#[macro_use]
extern crate penrose;

use penrose::{
	core::{config::Config, helpers::index_selectors},
	logging_error_handler,
	xcb::new_xcb_backed_window_manager,
	Backward, Forward, Less, More, Result,
};

fn main() -> Result<()> {
	let config = Config::default();
	let hooks = vec![];

	let key_bindings = gen_keybindings! {
		"M-j" => run_internal!(cycle_client, Forward);
		"M-k" => run_internal!(cycle_client, Backward);
		"M-S-j" => run_internal!(drag_client, Forward);
		"M-S-k" => run_internal!(drag_client, Backward);
		"M-S-q" => run_internal!(kill_client);
		"M-Tab" => run_internal!(toggle_workspace);
		"M-bracketright" => run_internal!(cycle_screen, Forward);
		"M-bracketleft" => run_internal!(cycle_screen, Backward);
		"M-S-bracketright" => run_internal!(drag_workspace, Forward);
		"M-S-bracketleft" => run_internal!(drag_workspace, Backward);
		"M-grave" => run_internal!(cycle_layout, Forward);
		"M-S-grave" => run_internal!(cycle_layout, Backward);
		"M-A-Up" => run_internal!(update_max_main, More);
		"M-A-Down" => run_internal!(update_max_main, Less);
		"M-A-Right" => run_internal!(update_main_ratio, More);
		"M-A-Left" => run_internal!(update_main_ratio, Less);
		"M-A-Escape" => run_internal!(exit);
		"M-m" => run_internal!(rotate_clients, Backward);
		"M-semicolon" => run_external!("dmenu_run");
		"M-Return" => run_external!("alacritty");

		refmap [ config.ws_range() ] in {
			"M-{}" => focus_workspace [ index_selectors(config.workspaces().len()) ];
			"M-S-{}" => client_to_workspace [ index_selectors(config.workspaces().len()) ];
		};
	};

	let mut wm = new_xcb_backed_window_manager(config, hooks, logging_error_handler())?;
	wm.grab_keys_and_run(key_bindings, map! {})?;

	Ok(())
}

**Comment by augusto-mantilla** [comment]
By the way, really cool project! I've been using it for some weeks and I really enjoy it. Thank you!

**Comment by sminez** [comment]
I'm going to guess that the call to apply the layout after the rotation is applied isn't happening for some reason. I'll take a look and see if I can spot why that is.

**Comment by sminez** [comment]
This (:point_up: ) adds testing around making sure that layout application is triggered for the appropriate public methods on the window manager. There's definitely more to check eventually but this _should_ resolve the issue. Are you able to confirm from your end @augusto-mantilla ?

**Comment by augusto-mantilla** [comment]
@sminez Yes, it's working perfectly now. Thanks a lot!
