### ISSUE TITLE
update_max_main turns a side_stack into a bottom_stack

### ISSUE THREAD

**Issue by kuity** [sminez/penrose#147]
### Describe the bug

When I enter the key sequence for update_max_main as below:
```
        "M-A-Up" => run_internal!(update_max_main, More);
```
The active workspace which has a side_stack layout turns into a bottom_stack layout.

### To Reproduce

1. Go to a new workspace
2. Open 2 terminals (by default, this is side_stack)
3. Enter "M-A-Up"

### Expected behavior

Nothing should happen as it should just increase the maximum number of clients by 1?

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- Penrose Version: 0.2

### Additional context

My config below, pretty much default settings.
[sample.txt](https://github.com/sminez/penrose/files/5999650/sample.txt)

**Comment by sminez** [comment]
This is not a bug... You are increasing the number of clients in the main area by one...which means both clients are placed in the main area, one above the other.

That is how side stack works.

If you open more terminals you will see that they stake to the right of those two as expected.
