### ISSUE TITLE
Alternative keyboard layout - am I doing this right ?

### ISSUE THREAD

**Issue by midnightexigent** [sminez/penrose#165]
Hi, first of all, thanks for this awesome library. 

I'm just starting out with penrose. I use a French (AZERTY) keyboard. So I have a file `/etc/X11/xorg.conf.d/00-keyboard.conf` which sets the keyboard layout following [this arch wiki article](https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration)

The problem I had is that X11 seems to run the `.conf` files after `.xinitrc`. Which means that penrose runs with the wrong keycodes. 

A quick and dirty solution was to remove the `00-keyboard.conf` file and add `setxkbmap fr` in `.xinitrc` which now looks like this: 

```bash
#!/bin/bash

setxkbmap fr
exec awesome-penrose &> ~/.penrose.log
```

Is this the right way to do it ? Or is there some sort of API that allows me to implement a listener for keyboard layout changes and update the HashMap accordingly ?

**Comment by sminez** [comment]
I'm afraid that for the moment, yeah the quick and dirty solution is the only one available. Penrose doesn't listen for keyboard mapping changes yet and doing so will require a little bit of a rewrite of the logic that parses keybindings. (at the moment, it maps the key names to key codes and then drops the keynames: we'd need to keep the original names to be able to re-run the generation).

Feel free to raise an issue asking for updating keybindings while Penrose is running (referencing this one).
