### ISSUE TITLE
Am I able to use "wmctrl -d" command to determine which current workspace I am in?

### ISSUE THREAD

**Issue by Joe23232** [sminez/penrose#169]
Hi, I wanted to know am I able to determine which current workspace I am in, as well as the name of all the workspaces in `penrose` if I ran [`wmctrl -d`](https://linux.die.net/man/1/wmctrl) command?

**Comment by sminez** [comment]
Please use the issue templates in future.

Short answer is yes, this should work. But arbitrary commands from wmctrl will most likely not work. Exactly which ones work / don't work I don't know and supporting external control via programs like wmctrl is not explicitly supported

**Comment by Joe23232** [comment]
> Please use the issue templates in future.

![image](https://user-images.githubusercontent.com/34926497/112746978-2fb83a80-8ffe-11eb-8ce7-5e1c588e167d.png)

Sorry bro but I don't see an appropriate issue template for a question related issue, do you want me to use the feature request issue template?

> Short answer is yes, this should work. But arbitrary commands from wmctrl will most likely not work. Exactly which ones work / don't work I don't know and supporting external control via programs like wmctrl is not explicitly supported

I see thanks
