### ISSUE TITLE
Is there a way to determine what current workspace I am in in penrose?

### ISSUE THREAD

**Issue by Joe23232** [sminez/penrose#170]
_Sorry I can't find a template which is not related to "bug Report" and "feature request"_

Is there a way to determine which current workspace I am in within Penrose?

**Comment by legendofmiracles** [comment]
You can add another hook to whenever you switch a workspace. The second (or first :thinking:?) argument is the new workspace.

**Comment by Joe23232** [comment]
So by default it doesn't have workspaces?

**Comment by sminez** [comment]
https://docs.rs/penrose/0.2.0/penrose/struct.WindowManager.html#method.active_workspace

Please read the documentation. All public methods are documented

**Comment by Joe23232** [comment]
Ok thanks
