### ISSUE TITLE
Center float windows

### ISSUE THREAD

**Issue by ghost** [sminez/penrose#185]
Hi! I've just started using penrose (loving it), and I'm trying to build a very minimal config, but I can't figure out how center float windows.

**Comment by sminez** [comment]
Hi @luizbra , glad you're enjoying Penrose! There's no direct support for centering floating windows, but you should be able to auto center any window you like using a Hook when the window is spawned. If you have a look at the scratchpad extension that should hopefully give you an idea of what's involved 🙂
