### ISSUE TITLE
Can't get multi monitor work well

### ISSUE THREAD

**Issue by cherryramatisdev** [sminez/penrose#190]
### Describe the bug

I can't get multiple monitors setup with own workspace per monitor,

Once I try to switch workspaces both monitors just change windows.

### To Reproduce

1. Open some terminals on first workspace.
2. Switch to second workspace and both monitors will change

### Expected behavior

I expect to have each monitor it's own set of workspaces and I want to change monitor only when I move my mouse or use the keybind.

### Versions & OS Details

- OS: Linux
- Distribution Arch Linux(Arco Linux)
- Penrose Version 0.2.0
![image](https://user-images.githubusercontent.com/86631177/140234102-f04c4a65-5f3a-4b4e-bde7-5ebad05f847d.png)

### Additional context

My config:

```rust
#[macro_use]
extern crate penrose;

use my_window_manager::{
    Conn, BLACK, BLUE, BROWSER, FONT, GREY, HEIGHT, LAUNCHER, MON_1, MON_2, TERMINAL, WHITE,
};
use penrose::{
    contrib::hooks::AutoSetMonitorsViaXrandr,
    core::{config::Config, data_types::RelativePosition, helpers::index_selectors, hooks::Hooks},
    draw::{dwm_bar, Color, TextStyle},
    logging_error_handler,
    xcb::{new_xcb_backed_window_manager, XcbDraw},
    Backward, Forward, Less, More, Result, Selector,
};

fn main() -> Result<()> {
    let workspaces = vec!["1", "2", "3", "4", "5", "6", "7", "8", "9"];
    let config = Config::default()
        .builder()
        .workspaces(workspaces)
        .build()
        .unwrap();

    let bar = dwm_bar(
        XcbDraw::new()?,
        HEIGHT,
        &TextStyle {
            font: FONT.to_string(),
            point_size: 14,
            fg: Color::try_from(WHITE)?,
            bg: Some(Color::try_from(BLACK)?),
            padding: (2.0, 2.0),
        },
        Color::try_from(BLUE)?, // highlight
        Color::try_from(GREY)?, // empty_ws
        config.workspaces().clone(),
    )?;

    let hooks: Hooks<Conn> = vec![
        AutoSetMonitorsViaXrandr::new(MON_1, MON_2, RelativePosition::Above),
        Box::new(bar),
    ];

    let key_bindings = gen_keybindings! {
        // Launch stuff
        "M-semicolon" => run_external!(LAUNCHER);
        "M-Return" => run_external!(TERMINAL);
        "M-w" => run_external!(BROWSER);

        // Exit penrose
        "M-S-q" => run_internal!(exit);
        "M-x" => run_external!("arcolinux-logout");

        // client management
        "M-j" => run_internal!(cycle_client, Forward);
        "M-k" => run_internal!(cycle_client, Backward);
        "M-S-j" => run_internal!(drag_client, Forward);
        "M-S-k" => run_internal!(drag_client, Backward);
        "M-f" => run_internal!(toggle_client_fullscreen, &Selector::Focused);
        "M-q" => run_internal!(kill_client);

        // workspace management
        "M-Tab" => run_internal!(toggle_workspace);
        "M-A-period" => run_internal!(cycle_workspace, Forward);
        "M-A-comma" => run_internal!(cycle_workspace, Backward);

        // Layout management
        "M-grave" => run_internal!(cycle_layout, Forward);
        "M-S-grave" => run_internal!(cycle_layout, Backward);
        "M-A-k" => run_internal!(update_max_main, More);
        "M-A-j" => run_internal!(update_max_main, Less);
        "M-A-h" => run_internal!(update_main_ratio, More);
        "M-A-l" => run_internal!(update_main_ratio, Less);
        "M-bracketright" => run_internal!(cycle_screen, Forward);
        "M-bracketleft" => run_internal!(cycle_screen, Backward);
        "M-S-bracketright" => run_internal!(drag_workspace, Forward);
        "M-S-bracketleft" => run_internal!(drag_workspace, Backward);

        refmap [ config.ws_range() ] in {
            "M-{}" => focus_workspace [ index_selectors(config.workspaces().len()) ];
            "M-S-{}" => client_to_workspace [ index_selectors(config.workspaces().len()) ];
        };
    };

    let mut wm = new_xcb_backed_window_manager(config, hooks, logging_error_handler())?;
    wm.grab_keys_and_run(key_bindings, map! {})
}

```

**Comment by sminez** [comment]
Hi @cherryramatisdev ,

This isn't a bug I'm afraid: the way Penrose handles workspace switching for multi-monitor is a little different from what you might expect and very much by design (I never found a WM that did what I wanted which is part of why I wrote Penrose in the first place).

> I expect to have each monitor it's own set of workspaces

This is not how Penrose works: there is one set of workspaces which are shared between all monitors.

When you start a new session you will have workspace 1 on monitor 1 and workspace 2 on monitor 2. If you change to workspace 2 with the `focus_workspace` method, it will jump you to the screen currently displaying that workspace (if it is visible) or swap the active workspace for the one requested (if it is _not_ currently visible).

Hope that helps 🙂

**Comment by cherryramatisdev** [comment]
Oh ok I understand, I'll try to adapt myself then, I love everything about how Penrose works, It's really an xmonad made right

I have another question about keybindings, If I need to create another issue about it, just say

It's that I can't bind my workspace keys like your configuration(and examples on the repo) without getting LSP errors, it's the docs right?
![image](https://user-images.githubusercontent.com/86631177/140324498-7394cc6c-51cd-4b25-b73b-cb24e3d63d4c.png)

LSP errors:

![image](https://user-images.githubusercontent.com/86631177/140324793-d70d2954-4313-46b7-bab3-1f438e211189.png)

**Comment by sminez** [comment]
No worries 🙂 key bindings should all work fine provided you are using _either_ head of the develop branch (see examples in the repo) _or_ the latest version on crates.io (see examples on docs.rs)

I suspect you are referring to an example from one version and attempting to use it with the other

**Comment by cherryramatisdev** [comment]
Oh ok that makes sense, thanks!
