### ISSUE TITLE
Screens are in the wrong order

### ISSUE THREAD

**Issue by teo8192** [sminez/penrose#193]
### Describe the bug

On a multi-monitor setup, the screens could be in the wrong order.

### To Reproduce

1. Connect multiple monitors
2. Move a workspace from the leftmost screen to the right (or opposite)
3. The workspace is possibly moving to an unexpected screen

### Expected behavior

The screens should be ordered by their x-positions, not the order they appear first.

### Versions & OS Details

- OS: linux
- Distribution: Arch
- Penrose Version: cc36bea96eb9863a9c0ad42f42fe8c7cc2c78571

### Additional context

One possible solution could be to sort the screens in `Screens::update_known_screens` by their x-values before the screen id is assigned.

**Comment by sminez** [comment]
I've just had a look at your bugfix branch in your fork. If you want to raise PRs for these issues you've opened, please do. But raise them against each issue if possible
