### ISSUE TITLE
Penrose will not start if it is unable to grab keys

### ISSUE THREAD

**Issue by teo8192** [sminez/penrose#194]
### Describe the bug

If some program such as sxhkd has grabbed some keys before penrose is able to, penrose will crash.

### To Reproduce

1. in `.xinitrx`, start `sxhkd` with a config that collides with penrose keybinds
2. attempt `startx`
3. it will not start

### Expected behavior

Penrose starts, and could probably ignore keys that failed to bind.

### Versions & OS Details

- OS: linux
- Distribution: Arch
- Penrose Version: behavior first seen in c0a22b4f90f32ca2e763100e2fbb09f62e1af1c3

### Additional context

In the specified commit, in the function `grab_keys` in `src/xcb/api.rs`, the function `xcb::grab_key` was changed to `xcb::grab_key_checked` and a `?` was used on the result.
This caused the error (BadAccess) to propagate up and crash the window manager.

**Comment by sminez** [comment]
This is not a bug: if you have duplicate bindings between Penrose and an external program such as sxhkd then that _is_ an error.
