### ISSUE TITLE
Add a common place for both required and optional dependencies

### ISSUE THREAD

**Issue by Frixxie** [sminez/penrose#195]
### Is your feature request related to a problem? Please describe

It is hard to find out what external libraries the project is dependent on,
or is optional and what features these optional dependencies provide.
This would be nice so it can become easier to package the library in package managers.

### Describe the change / addition you'd like to see made

Either a section in README.md or an own DEPEND.md.

**Comment by sminez** [comment]
Penrose is not intended to use via package managers: it is a crate not a binary. Dependencies and whether or not they are optional are all visible in the Cargo.toml

**Comment by Frixxie** [comment]
My goal was not to package penrose itself in a package manager, but my own build.
In Cargo.toml it is possible find all crates penrose is dependent on, but when packaging for a package manager other external libraries should be specified.
Examples of this is x11-misc/xcb on Gentoo (libxcb on Arch).
