### ISSUE TITLE
XF86AudioMicMute keybind not found

### ISSUE THREAD

**Issue by rinkimekari** [sminez/penrose#200]
# Overview
Real quick, I love this window manager so far and it has become my main. It's super fun, so thank you for your hard work!

Here's the bug:
When trying to add a keybinding for my mic mute button, the compilation fails. Here is the info given by the rust compiler:
```
    = help: message: 'XF86AudioMicMute' is an invalid key binding: 'XF86AudioMicMute' is not a known key: run 'xmodmap -pke' to see valid key names
            Key bindings should be of the form <modifiers>-<key name> or <key name> e.g:  M-j, M-S-slash, M-C-Up, XF86AudioMute
    = note: this error originates in the macro `__private` (in Nightly builds, run with -Z macro-backtrace for more info)
```

# Reproduction Instructions
To reproduce the error simply add the XF86AudioMicMute keybinding to your main.rs:
```rust
// snip

fn main() -> Result<()> {

    // snip

    let keybindings = gen_keybindings! {

        // snip

        "XF86AudioMicMute" => run_external!("test command");

        // snip

    }

    // snip

}
```

# xmodmap output
Here is the output of `xmodmap -pke` relative to the issue:
```
. . .
keycode 198 = XF86AudioMicMute NoSymbol XF86AudioMicMute
. . .
```
so the keybind definitely exists for me, it just doesn't work for some reason on penrose

# Other info
I'm using Arch Linux and penrose is pulled directly from this github in my Cargo.toml, so it's v0.2.0

Thanks again for making this! I hope one day it can become widely known and supported!

**Comment by sminez** [comment]
Not all of the XF86 keys are currently supported I'm afraid. You can view the list of supported keys in the penrose_keysyms crate in the crates directory.

As a side note, if you're pulling from the repo in your cargo toml then you're not pulling v0.2.0: you're pulling head of this repo :slightly_smiling:

**Comment by rinkimekari** [comment]
Thanks! I'll look into a PR for the key I'm missing.

**Comment by rinkimekari** [comment]
PR #201 solved this, so I’m closing it.
