### ISSUE TITLE
Float window option similar to bspwm

### ISSUE THREAD

**Issue by tdfranklinaz** [sminez/penrose#208]
Is it already possible to spawn certain windows as floating or would this feature have to be added manually? I really like how bspwm implements this feature with the ability to spawn certain windows as floating or hotkey the focused window to make it float. 

I am willing to try writing this myself but my programming experience is limited in this field, any information in the right direction would be appreciated.

**Comment by sminez** [comment]
If you take a look at the [scratchpad extension](https://github.com/sminez/penrose/blob/develop/src/contrib/extensions/scratchpad.rs) you can see how you can grab certain windows and modify them using a hook. If I understand what it is you are after that should be flexible enough to get the job done I think.

**Comment by tdfranklinaz** [comment]
Thank you for a quick response. This is exactly what I'm looking for!
