### ISSUE TITLE
Confused about this keybindings deprecated error

### ISSUE THREAD

**Issue by MaybeAnonymous** [sminez/penrose#213]
### Describe the bug

Getting an error that makes me unable to compile Penrose ( default )
![image](https://user-images.githubusercontent.com/89218161/160250751-458c0b9b-b101-496a-8042-61fbf94a5be5.png)

### To Reproduce

1. Follow the getting started guide
2. Try to compile
3. See error

### Expected behavior

For it to compile and make a binary file in target/release

### Screenshots

![image](https://user-images.githubusercontent.com/89218161/160250775-4cc85e5b-a996-470c-8f71-0cc45805836e.png)
![image](https://user-images.githubusercontent.com/89218161/160250790-473429af-496f-4a39-af0d-36d735930b3a.png)

### Versions & OS Details

- OS: linux
- Distribution: Artix Linux
- Kernel Version: 5.16.14-artix1-1
- Penrose Version: in dependencies i set it to "0.2"
- Rustup: stable

**Comment by sminez** [comment]
Please read the documentation as mentioned in the error you have provided. The syntax for the keybindings macro was updated quite a while ago and the syntax you are using is no longer supported.

I'll get the getting started guide updated to use the correct syntax that is used in all of the compiler checked examples in the examples directory.
