### ISSUE TITLE
Zoom-feature like in dwm?

### ISSUE THREAD

**Issue by falbru** [sminez/penrose#216]
In dwm, you can zoom on to the focused client by pressing a configurable key binding. This swaps the focused client in the stack with the master client. I may be blind, but I can't seem to find a similar function in penrose. Personally, I'd like to do something like this: `"M-space" => run_internal!(zoom_on_client, &Selector::Focused);` in order to some on to the focused window.

Will this become a feature?

**Comment by sminez** [comment]
Not as a stand alone feature I suspect, no. Using the existing functionality you should be able to write something similar though I think? If you do and wish to contribute it then it could be added to the contrib directory if you wanted to raise a PR 👍

**Comment by falbru** [comment]
> Using the existing functionality you should be able to write something similar though I think?

I guess you could use the drag_client method until you position the two windows right, but that feels quite bodgy and inefficient.

> If you do and wish to contribute it then it could be added to the contrib directory if you wanted to raise a PR +1

I'd love to make a zoom extension, however I can't make it without changing the vanilla source code in penrose. In order to add a zoom_on_client method, I have to implement it for the WindowManager struct. However, the fields in WindowManager aren't public so I can't refer to them from my contrix/extensions/zoom.rs file (the WindowManager struct is defined in core/manager/mod.rs). I have no experience with Rust, so there might be an obvious work-around, but I think the only solution to this problem is making the fields public. I'm also experiencing other scope-related issues when trying to implement this zoom feature. I don't feel confident enough in Rust to mess with your source code, so I just have to give up for the time being.

I did manage to successfully add the zoom feature by hardcoding the zoom_on_client function into the core/manager/mod.rs file (where all the other methods like drag_client are). If this feature isn't desired in the vanilla penrose project, I'll just keep this in my own, personal fork of penrose.

Lastly, I want to congratulate you on making such a awesome project. Penrose is EXACTLY what I've been looking for in a window manager!
