### ISSUE TITLE
Emacs starts with a blank splash screen on startup

### ISSUE THREAD

**Issue by markmelix** [sminez/penrose#219]
### Describe the bug

When I start Emacs in penrose, I see a blank splash screen and I can't interact with Emacs. If I run Emacs in floating mode, it works as expected and I can interact with it, so maybe this problem is related to window positioning, I don't know. This problem is only related to penrose because I can use Emacs in other window managers (tested in i3 and awesome).

### To Reproduce

1. Run penrose
2. Launch Emacs
3. See white screen

### Expected behavior

I can interact with Emacs.

### Screenshots

![image](https://user-images.githubusercontent.com/83908547/173363291-00d6bc4e-9804-4c2d-a5ec-594ad34f4367.png)

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- OS Version: 5.18.3-arch1-1
- Penrose Version: 0.2.1

### Additional context

- [My config](https://github.com/markmelix/wm)
- Minimal main.rs that reproduces the issue:
```rust
#[macro_use]
extern crate penrose;

use penrose::{
	core::{config::Config, helpers::index_selectors},
	logging_error_handler,
	xcb::new_xcb_backed_window_manager,
	Backward, Forward, Less, More, Selector,
};

use simplelog::{LevelFilter, SimpleLogger};

// Replace these with your preferred terminal and program launcher
const TERMINAL: &str = "alacritty";
const LAUNCHER: &str = "dmenu_run";

fn main() -> penrose::Result<()> {
	// Initialise the logger (use LevelFilter::Debug to enable debug logging)
	if let Err(e) =
		SimpleLogger::init(LevelFilter::Info, simplelog::Config::default())
	{
		panic!("unable to set log level: {}", e);
	};

	let config = Config::default();
	let key_bindings = gen_keybindings! {
		// Program launchers
		"M-semicolon" => run_external!(LAUNCHER);
		"M-Return" => run_external!(TERMINAL);

		// Exit Penrose (important to remember this one!)
		"M-A-C-Escape" => run_internal!(exit);

		// client management
		"M-j" => run_internal!(cycle_client, Forward);
		"M-k" => run_internal!(cycle_client, Backward);
		"M-S-j" => run_internal!(drag_client, Forward);
		"M-S-k" => run_internal!(drag_client, Backward);
		"M-S-f" => run_internal!(toggle_client_fullscreen, &Selector::Focused);
		"M-S-q" => run_internal!(kill_client);

		// workspace management
		"M-Tab" => run_internal!(toggle_workspace);
		"M-A-period" => run_internal!(cycle_workspace, Forward);
		"M-A-comma" => run_internal!(cycle_workspace, Backward);

		// Layout management
		"M-grave" => run_internal!(cycle_layout, Forward);
		"M-S-grave" => run_internal!(cycle_layout, Backward);
		"M-A-Up" => run_internal!(update_max_main, More);
		"M-A-Down" => run_internal!(update_max_main, Less);
		"M-A-Right" => run_internal!(update_main_ratio, More);
		"M-A-Left" => run_internal!(update_main_ratio, Less);

		map: { "1", "2", "3", "4", "5", "6", "7", "8", "9" } to index_selectors(9) => {
			"M-{}" => focus_workspace (REF);
			"M-S-{}" => client_to_workspace (REF);
		};
	};

	let mut wm =
		new_xcb_backed_window_manager(config, vec![], logging_error_handler())?;

	spawn!("emacs -Q")?;

	wm.grab_keys_and_run(key_bindings, map! {})
}
```

**Comment by sminez** [comment]
I run Emacs under Penrose and have never encountered this issue...

In the main.rs you provide you are starting Emacs before kicking off the main event loop for the window manager. Do you still have the issue if you launch Emacs manually once Penrose is running?

**Comment by markmelix** [comment]
I've tried running Emacs after wm startup using terminal and still have the issue. The only thing I can interact with is a menu bar and I can click the modeline and see context menus, but I don't see the result of acting with them. 

Also, I use [emacs-native-comp-git-enhanced](https://aur.archlinux.org/packages/emacs-native-comp-git-enhanced) package from aur. Maybe it matters?

**Comment by markmelix** [comment]
Alright, it's gccemacs' issue. I've tried uninstalling gccemacs and installing just emacs without native compilation features and it works, I can interact with it. The strange thing is that I have no issues with gccemacs in other window managers like i3 or awesome.
