### ISSUE TITLE
help , please: How can you add gaps?

### ISSUE THREAD

**Issue by Pandademic** [sminez/penrose#220]
Good day!
Thank 
In the screenshot in the readme , there are gaps in between the windows.

I'd just like to know how can you achive that?

Thank you for making this awesome library!

**Comment by markmelix** [comment]
Hey! You can adjust the gap size using the [`Config struct`](https://docs.rs/penrose/latest/penrose/struct.Config.html). By default, it's being created using [`Default trait`](https://docs.rs/penrose/latest/penrose/struct.Config.html#impl-Default) to be initialized with the default configuration, but you can create your own variant of this struct with own parameters using [`ConfigBuilder struct`](https://docs.rs/penrose/latest/penrose/core/config/struct.ConfigBuilder.html) (you can get it with [`Config::builder method`](https://docs.rs/penrose/latest/penrose/struct.Config.html#method.builder)), just like this:
```rust
// ...
let gap_size = 5; // gap between tiled windows in pixels
let config = Config::builder().gap_px(gap_size).build()?;
let mut wm = new_xcb_backed_window_manager(config, hooks, logging_error_handler())?;
// ...
```
There're other settings you can change like status bar height or border width of each window and others, just see [`ConfigBuilder struct`](https://docs.rs/penrose/latest/penrose/core/config/struct.ConfigBuilder.html) methods for more high-level configuration options.

**Comment by Pandademic** [comment]
@markmelix thanks for the quick reply! 

That's answer's my , question , it does.

**Comment by markmelix** [comment]
You're very welcome! Maybe you should close the issue, then.

**Comment by Pandademic** [comment]
done!
