### ISSUE TITLE
Symmetrical default layouts

### ISSUE THREAD

**Issue by beaumccartney** [sminez/penrose#221]
### The problem

There are layout options for a stack on the on the right or the bottom (`core::layout::side_stack` and `core::layout::bottom_stack` respectively), but no options for a stack on the top or the left.

### Describe the change / addition you'd like to see made

Implement `top_stack()` and `left_stack()`, and rename `side_stack()` to `right_stack()`

I'm working on this on a fork atm, I'll make a pr if you're interested.

### Alternatives

Rename `bottom_stack()` to `vertical_stack()` (or something idk man), add a bool argument to the stack functions that determines which side the main region will be on.

Less redundant code but afaik (if I'm wrong mbmb) all layout functions need to have all the same arguments.

EDIT: This isn't possible I just saw the trait bound (LayoutFunc) for `Layout::new()`. That's my bad.

**Comment by sminez** [comment]
Changing the default layouts will be a breaking API change, especially given that the layouts in question are referenced in the examples.

Layouts are (by design) simple to implement and extend. Would you be ok with instead adding these new layouts to the contrib directory please?

**Comment by beaumccartney** [comment]
Sure thing, no worries at all. I'll still name them `bottom_stack` and `left_stack` cause I can't think of anything better.

EDIT: sorry I meant `top_stack`, not bottom stack. My bad.
