### ISSUE TITLE
Simple way to apply particular layout

### ISSUE THREAD

**Issue by ZaheenJ** [sminez/penrose#225]
### Is your feature request related to a problem? Please describe

Is there a simple way to set a keybind to activate a particular layout? Unless I just missed it in the docs which I might have I only see the `cycle_layout` method. I see that there is already a method that does what I describe, `try_set_layout`  but it is only implemented on `Workspace` and not `WindowManager` making it a hassle to use with `gen_keybindings!`.

### Describe the change / addition you'd like to see made

```
let keybindings = gen_keybindings! {
        "M-b" => run_internal!(try_set_layout, "B"); // Bottom Stack
        "M-t" => run_internal!(try_set_layout, "T"); // Side Stack
        "M-f" => run_internal!(try_set_layout, "F"); // Monocle/Fullscreen
}
```
Being able to something like that would be convenient. Since the try_set_layout method is already there for `Workspace` it shouldn't be much work to implement it on `WindowManager` which is what I ended up doing in [my own fork](https://github.com/ZaheenJ/penrose/tree/try_set_layout). I can make a pull request if you like it but it modifies core.

### Describe alternatives you've considered

At first I tried copying what `run_internal!` does manually so that I could get access to the `try_set_layout` method workspaces like this:
```
let keybindings = gen_keybindings! {
        "M-b" => Box::new(|wm: &mut WindowManager<_>| {
            wm.active_workspace_mut().try_set_layout("B");
            Ok(())
        });
}
```
This kind of worked but when I used the keybind I had to switch to another workspace and back to see the layout actually change maybe because of some hook not getting run or something, but either way this is not ergonomic at all so I just decided to fork and just copied `cycle_layout`  for `Workspaces` but made it work with the `try_set_layout` method on `Workspace`.

**Comment by sminez** [comment]
Ah, your example you give at the end should work so long as you [trigger a layout for the windows on the screen in question](https://docs.rs/penrose/latest/penrose/struct.WindowManager.html#method.layout_screen) (setting the active layout for a workspace only sets what will be used next time a layout is applied). The `cycle_layout` method looks like this:

```rust
    pub fn cycle_layout(&mut self, direction: Direction) -> Result<()> {
        let wix = self.screens.active_ws_index();
        self.workspaces.cycle_layout(wix, direction);
        self.run_hook(HookName::LayoutChange(wix));
        self.apply_layout(wix)
    }
```

so I suspect you want to try something like the following (note that layout hooks will _not_ fire for this):
```rust
let keybindings = gen_keybindings! {
        "M-b" => Box::new(|wm: &mut WindowManager<_>| {
            wm.active_workspace_mut().try_set_layout("B");
            wm.layout_screen(0)
            Ok(())
        });
}
```

**Comment by beaumccartney** [comment]
Is there any way to achieve what your example does, and fire layout hooks?

**Comment by sminez** [comment]
Ah wait, I'm an idiot: apply_layout does fire the hooks :facepalm:
