### ISSUE TITLE
poll for event

### ISSUE THREAD

**Issue by brainwave0** [sminez/penrose#230]
### Is your feature request related to a problem? Please describe

I would like to use Penrose in my project which will move the desktop based on where the user is looking, but in order to do so I would need a way to run my face-tracking function continuously, and I do not see a way to do so with Penrose in it's current state.

### Describe the change / addition you'd like to see made

I suggest allowing `wait_for_event` to be swapped with `poll_for_event` in the main loop, perhaps as an argument to `grab_keys_and_run`.

### Describe alternatives you've considered

I looked at all the hooks, and the most appropriate one would be `EventHandled`, but this only runs when there is an event, so for my project this would mean I can't look around unless I am also doing something like moving the cursor to trigger events.

**Comment by sminez** [comment]
If I'm honest, this doesn't sound like a great idea...the window manager event loop really isn't a good place to inject real time face tracking logic. One thing you could do is spawn the face tracking logic off in a thread and have that generate keypress events to trigger the desktop moves?

In some of the attempted rewrites of the internals of Penrose I've looked at allowing for user generated events to be submitted via a channel but that's nowhere near usable yet I'm afraid.

**Comment by brainwave0** [comment]
Okay then. I think I'll just look for some other way to do it.

Why is it not a good idea to put it in the event loop?
