### ISSUE TITLE
Firefox pop-out confirmation window not displayed

### ISSUE THREAD

**Issue by greweln** [sminez/penrose#231]
### Describe the bug
Firefox pop-out confirmation window to not appear on the screen when downloading and overwriting an existing image.  I have to run the fullscreen keybind  to have it displayed on screen.

### To Reproduce

1. Saving an image from Firefox will pop-out the save location window: WM_NAME(STRING) = "Save Image"'
2. Overwriting an existing image, will pop-out a confirmation window in background(?),  with xpropr as: WM_NAME(STRING) = " "
3. Workaround: use fullscreen keybind which will display the confirmation window as full screen.

**Comment by sminez** [comment]
This should now be fixed as of ca9ea788b6d600f277fc95f9ce76773464292257

@greweln would you be able to confirm that Firefox dialogues now work for you when running from the latest `develop` commit?

**Comment by greweln** [comment]
@sminez 
Yes, it looks good. If I may suggest... to have  the pop window spawned  in the middle of the screen instead of the middle of the focused window? 
Thanks a lot for this!

**Comment by sminez** [comment]
Great! Spawning in the middle of the screen is what I originally had :female_facepalm: I'll put it back to that now and then get this closed off

**Comment by sminez** [comment]
Gets things centred on the screen rather than inside the parent 36de5d4d46211efbdfc02b99528bc44792d5c22f :+1:
