### ISSUE TITLE
window swalloing 

### ISSUE THREAD

**Issue by mrfluffy-dev** [sminez/penrose#232]
### Is your feature request related to a problem? Please describe

I want to make a window swallower so that if I open mpv for example in alacritty then the alacritty window hides and the mpv window takes its place and then again if mpv closes alacrity comes back. bun in order to do that I must get the parent pid of the mpv window in this case and as far as I can tell penrose doesn't have this. 

### Describe the change / addition you'd like to see made

I would like a ppid option in penrose or even better a window swallowing option.

### Describe alternatives you've considered

an even better option would be a window swallowing function that takes a class name that swallows windows that spawns from it. for example 
```rust
use penrose::contrib::swallow;
let term_swallow = swallow::new("alacritty");
let hooks: XcbHooks = vec![
    ...,
    term_swallow.get_hook(),
];
```
### Additional context

I don't have a solution in rust at the moment but This is how I do it in qtile
```python
@hook.subscribe.client_new
def _swallow(window):
    pid = window.window.get_net_wm_pid()
    ppid = psutil.Process(pid).ppid()
    cpids = {c.window.get_net_wm_pid(): wid for wid, c in window.qtile.windows_map.items()}
    for i in range(5):
        if not ppid:
            return
        if ppid in cpids:
            parent = window.qtile.windows_map.get(cpids[ppid])
            parent.minimized = True
            window.parent = parent
            return
        ppid = psutil.Process(ppid).ppid()

@hook.subscribe.client_killed
def _unswallow(window):
    if hasattr(window, 'parent'):
        window.parent.minimized = False
```

**Comment by mrfluffy-dev** [comment]
Xmonad also has this functionality 
https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Hooks-WindowSwallowing.html#v:swallowEventHook

**Comment by sminez** [comment]
Implementing something like this should be possible in the `0.3.0` rewrite i've been working on [here](https://github.com/sminez/penrose/tree/rewrite). I'll take a look once I've finished stabilising the core functionality 👍

**Comment by sminez** [comment]
Right, had a chance to take a look at this one and something like the following works for nabbing the parent pid chain if you know the process ID:
```rust
// Parsing based on the format for /proc/pid/stat from https://man.archlinux.org/man/proc.5
// This will bottom out when the parent pid hits root (0) due to there being no stat file for root
fn parent_pid(pid: u32) -> Option<u32> {
    let stat = std::fs::read_to_string(format!("/proc/{pid}/stat")).ok()?;
    let s_parent_pid = stat.split_whitespace().nth(3).expect("/proc to be valid");

    s_parent_pid.parse().ok()
}

fn parent_pid_chain(mut pid: u32) -> Option<Vec<u32>> {
    let mut parents = vec![];

    while let Some(parent) = parent_pid(pid) {
        parents.push(parent);
        pid = parent;
    }

    Some(parents)
}
```

As for getting the pid of the process in question, you can use the `XConn::get_prop` method to pull the value of `_NET_WM_PID` which should come back as a Cardinal containing the appropriate u32 (assuming the program sets this property).

Taking a look at the XMonad implementation you've linked to I think this would likely end up somewhat similar with a state extension for storing the details of windows that have been swallowed and then an event hook that intercepts and handles the appropriate XEvents.

I've got maybe 50% of an initial implementation together at this point I think? I'll keep digging in to it and see how far I get.

**Comment by sminez** [comment]
This is just a rough draft for now: it's not been tested out and I'm actually _reasonably_ confident that the state tracking isn't going to be quite right yet. It gets the idea across though 🙂

**Comment by sminez** [comment]
@mrfluffy-dev if you are still interested in this can you please try it out and let me know if it behaves as you expect?

**Comment by mrfluffy-dev** [comment]
Yes I will take a look thanks for the work.

**Comment by mrfluffy-dev** [comment]
First need to fix all the API changes from 0.2 to 0.3

**Comment by dee-sea** [comment]
Hi,
I'm joining the discussion. I'm porting my old config to the 0.3 version and I just seen this extesion n the doc, but I don't understang what "Query" should be passed. Can I get an example, I'm quite interested too.

**Comment by sminez** [comment]
You probably just want to use one of the provided ones rather writing your own: https://docs.rs/penrose/latest/penrose/x/query/index.html

In general, it's best to use the program name or X class.

**Comment by dee-sea** [comment]
Thanks for the answer but I'm still not sure if I use it right. At leaset until now I have no results. What I did is:
Added :
let swallow_hook = WindowSwallowing::boxed(ClassName("st-256color"));
then added (in bold):
let config = add_ewmh_hooks(Config {
        default_layouts: layouts(
            config_from_file.n_main,
            config_from_file.ratio,
            config_from_file.gap_width,
            config_from_file.gap_width,
            config_from_file.bar_height,
        ),
        border_width: config_from_file.border_width,
        focused_border: config_from_file.green.into(),
        normal_border: config_from_file.red.into(),
        **event_hook: Some(swallow_hook),**
        startup_hook: Some(startup_hook),
        ..Config::default()
    });

I see a reference to swalloning in the logs when a client is destroyed but noting happens when the client is created.

**Comment by sminez** [comment]
Sorry for not seeing your update about this. If you are still interested in this functionality and are having issues could you please reopen this issue and attach some log output of the behaviour you are seeing when the swallowing is failing to trigger correctly?
