### ISSUE TITLE
System Tray

### ISSUE THREAD

**Issue by itcreator** [sminez/penrose#234]
### System Tray

Is it possible to add system tray to top panel?

**Comment by sminez** [comment]
Not to the panel provided from this crate as currently implemented, no. It should be possible to write a widget for doing it but I've not taken a proper look at it I don't think.

**Comment by itcreator** [comment]
@sminez thank you for your response.
Probably you can suggest some helpful documentation about implementation system tray on rust for developer who never code linux UI?

**Comment by sminez** [comment]
It's not something I know much about to be honest: which is why I've not coded it up myself 🙂
