### ISSUE TITLE
Support wayland as well as x11 could be deprecated within a few years.

### ISSUE THREAD

**Issue by Raj2032** [sminez/penrose#235]
As wayland is going to eventually take over x11 and become the mainstream display server over x11, I was wondering what would happen to penrose if x11 becomes depreciated? Wouldn't it be better to also have support for wayland, this is also better for performance wise?

**Comment by sminez** [comment]
Under Wayland the window manager is combined with the compositor. Supporting that isn't something I'm particularly interesting in tackling I'm afraid! I suppose the short answer is "if x11 does finally die, Penrose will likely die with it".

That said, x11 being fully deprecated any time soon isn't particularly likely I don't think.

**Comment by Raj2032** [comment]
I see thanks

**Comment by uncomfyhalomacro** [comment]
Sorry for the ping. @Raj2032 if you want, you can try https://github.com/mahkoh/jay. although not a library, it is an actual working example of a Wayland WM in Rust

**Comment by Raj2032** [comment]
@uncomfyhalomacro 

> Sorry for the ping. @Raj2032 if you want, you can try https://github.com/mahkoh/jay. although not a library, it is an actual working example of a Wayland WM in Rust

Dude I have been looking for something like this all along. Thanks mate =D

**Comment by itcreator** [comment]
@uncomfyhalomacro Thanks 
Looks great.

**Comment by Raj2032** [comment]
@uncomfyhalomacro @itcreator I believe owner has made mentions of support for wayland now:
https://github.com/sminez/penrose/issues/288
