### ISSUE TITLE
Error 'XF86Calculator' is an invalid key binding

### ISSUE THREAD

**Issue by itcreator** [sminez/penrose#236]
### Describe the bug

Unable to bind `XF86Calculator`  key

### To Reproduce

1. add key binding `"XF86Calculator" => run_external!(CALCULATOR);`
2. try to build window manager ` cargo build --release`
3. See an error
```
$ cargo build --release 
   Compiling window-manager v0.1.0 (/home/paranoid/projects/rust/window-manger)
error: proc macro panicked
   --> src/main.rs:51:24
    |
51  |       let key_bindings = gen_keybindings! {
    |  ________________________^
52  | |         // Program launchers
53  | |         "M-p" => run_external!(LAUNCHER);
54  | |         "M-grave" => run_external!(LAUNCHER);
...   |
100 | |          };
101 | |     };
    | |_____^
    |
    = help: message: 'XF86Calculator' is an invalid key binding: 'XF86Calculator' is not a known key: run 'xmodmap -pke' to see valid key names
            Key bindings should be of the form <modifiers>-<key name> or <key name> e.g:  M-j, M-S-slash, M-C-Up, XF86AudioMute
    = note: this error originates in the macro `__private` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `window-manager` due to previous error
```

### Expected behavior

Application is built.

### Screenshots

![image](https://user-images.githubusercontent.com/928509/191098899-19c58067-c7cb-4e5f-882a-c8329fe0a8fb.png)

### Versions & OS Details

- OS: [e.g. linux/fedora]
- OS Version [e.g. 36]
- Penrose Version [#0.2.1]

### Additional context

!!! Other `XF86*`  bindings works correctly

```
$ xmodmap -pke | grep XF86Calculator
keycode 148 = XF86Calculator NoSymbol XF86Calculator
```

**Comment by acid-bong** [comment]
Have you checked the name for it with xev?

**Comment by itcreator** [comment]
Sure. 
It returns XF86Calculator

```
keycode 148 (keysym 0x1008ff1d, XF86Calculator)
```

**Comment by jasperspahl** [comment]
I think the problem is that not all keycodes defined in `X11/XF86keysym.h` are also defined in [crates/penrose_keysyms/src/lib.rs](https://github.com/sminez/penrose/blob/af84307987fdfc0314c0b42570664e51d6af6d7f/crates/penrose_keysyms/src/lib.rs)
This issue is related to #138 and #140

**Comment by itcreator** [comment]
Thank you @jasperspahl 

Looks like it is definitely a problem of [crates/penrose_keysyms/src/lib.rs](https://github.com/sminez/penrose/blob/af84307987fdfc0314c0b42570664e51d6af6d7f/crates/penrose_keysyms/src/lib.rs). 
But I'm not sure that it is related to #138 and #140 because some other XF86 keys (that I use) works correctly even without modifiers.

**Comment by sminez** [comment]
The merging of the above PR should resolve this for you but you will currently need to pull penrose from GitHub. I am close to moving over to a fairly substantial rewrite of the project however so I'd make sure to pin to the specific commit rather than just HEAD of the develop branch.

https://github.com/sminez/penrose/commit/33af1c43add8c4e5a6ad98710e81f1178ab32686
