### ISSUE TITLE
Dynamic workspace list

### ISSUE THREAD

**Issue by Arc676** [sminez/penrose#240]
### Is your feature request related to a problem? Please describe

The status bar always shows all the available workspaces even if they are empty.

### Describe the change / addition you'd like to see made

It would be nice if there were an option to make the workspace list behave like i3, where only the active and occupied workspaces appear in the status bar. The empty ones are hidden and don't occupy any space in the status bar until they become used.

### Describe alternatives you've considered

I copy-pasted part of `bar.rs` to implement this myself while still depending on Penrose from `crates.io`, but it's somewhat inconvenient to have to recreate something from the crate to make this kind of change.

### Additional context

I have a working implementation (although maybe not an optimal one since I'm not too familiar with Penrose yet) but I thought I'd open an issue first to see if this kind of behavior is in line with what Penrose should contain rather than jumping straight to the PR.

**Comment by Arc676** [comment]
While looking through the docs I stumbled across [`RemoveEmptyWorkspaces`](https://docs.rs/penrose/0.2.1/penrose/contrib/hooks/struct.RemoveEmptyWorkspaces.html), which I guess already does this, but I have to check whether this preserves the desired order of workspaces when they become occupied.

EDIT: Maybe I'm not using it correctly but this doesn't seem to have the behavior I'm describing.

**Comment by sminez** [comment]
See #241 : the behaviour of the status bar is highly minimal and modelled after the stock dwm bar rather than anything with feature beyond displaying current workspace and simple text based information
