### ISSUE TITLE
Emacs Shrinks to Corner After Switching Workspaces

### ISSUE THREAD

**Issue by Corbanator** [sminez/penrose#256]
### Describe the bug
I recently started trying to get Emacs running on my machine. When I change workspaces, however, emacs shrinks up into the corner and I have to restart emacs to get it back to normal
...

### To Reproduce

- Arch Linux
- Penrose on its own (no Desktop Environment)
- Doom Emacs with the emacs-nativecomp package
- open emacs
- switch workspaces
- switch back
- emacs is now tiny and in the top-left corner

### Expected behavior

Emacs should remain the same size when switching between workspaces

### Screenshots

![emacs_troubles](https://user-images.githubusercontent.com/44687886/217129250-63a7e848-0362-4f6c-bb70-20fdd36be116.png)

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- Penrose Version: 0.3.1

### Additional context

- [ ] minimal main.rs that reproduces the issue
- [ ] debug log output:

**Comment by sminez** [comment]
Without the additional context requested in the issue template there isn't really anything I can do to help I'm afraid. I've made use of Emacs under Penrose on Arch and had no issues so at least part of the problem is going to be down to your local set up I suspect.

**Comment by Corbanator** [comment]
In my case I was able to fix it by switching to a version of emacs with pgkt. I totally forgot that I had put up an issue and forgot to close it; sorry for wasting your time.

**Comment by sminez** [comment]
That's alright! Sorry I didn't see this and respond sooner
