### ISSUE TITLE
Increase Keybindings functionality. 

### ISSUE THREAD

**Issue by alextreichler** [sminez/penrose#260]
Hello,

Is it possible to have keybindings similar to emacs? For Example, I currently use xmonad and have a keybinding as follows...

M-b w  # this opens up my browser in "work" profile
M-b p  # this opens my browser in "personal" profile.

Essentially, looking to start a key sequence.  Thank you.

**Comment by sminez** [comment]
Not using the current mechanism I'm afraid, no. You would need to track and clear "modes" in response to certain key presses which would require a rewrite of the key handling layer.

It might be possible to get something similar if you wrote an extension that intercepted all key presses? You could track being in a given mode in a state extension and modify how key presses were interpreted in response to the active mode?

**Comment by alextreichler** [comment]
Thank you for the response. My knowledge with Rust is not there yet, but might be an interesting project in the future.
