### ISSUE TITLE
Question: spawned floating windows 

### ISSUE THREAD

**Issue by greweln** [sminez/penrose#262]
First of all thanks for this project!

The issue that I'm having is about Firefox's spawn windows (Save as, Confirm override etc) which they spawn on a different monitor and often are not clickable (in a sense that I cannot change the path/name of the file)

![screenshot](https://user-images.githubusercontent.com/78338967/230425535-447c1d79-66f6-4d26-bd19-2b8593dc4f9f.png)

I'm running Penrose on a minimal Fedora system.

Any suggestions? I can't seem to find a way to fix this
Thanks

**Comment by sminez** [comment]
Hi @greweln , sorry about this one. It's one I've know about for a while but not really managed to nail down _why_ it's happening. Sub windows like this from Firefox behave in a bit of an odd way that I've not been able to completely pin down. If I'm honest, last time I looked I gave up and switched to using chromium...

I don't have much time to work on it at the moment but I can try and take a look with fresh eyes and see if I can make progress on it. As and when I find anything I'll share thoughts and notes on this issue.

One thing that would help would be to confirm if this only happens with Firefox or if other programs are still affected as well? If you could run xprop on the save dialogue for me and share the output that would help as well.

**Comment by greweln** [comment]
@sminez  thanks for the reply.
Here are some more details about this:

1. Defining a specific sized floating window behaves as desired (the window spawns in the centre of current monitor, I can do changes on it ):
```
let firefox_save_image = (Title("Save Image"), FloatingCentered::new(0.3, 0.3));
Config {
     manage_hook: Some(Box::new(firefox_save_image))
     ...
}
```
2. apparently I have to do this for every dialog sub-window ? as xprop returns different WM_NAME(STRING): 
`"Save Image"` 
`"Enter name of file to save to…",` 
`"<none>",`  
 etc. 
but I'm kind of stuck figuring out how to define multiple managed hooks. Some  help would be much appreciated :)
4. I can't really say if this behaviour applies to other programs since all my programs are terminal based apps.

**Comment by sminez** [comment]
You definitely shouldn't have to do this for every sub-window... (that's not at all feasible 😬) but hooks should compose together using the **then** and **then_boxed** methods.

I'm the same as you with my browser being pretty much the only non-terminal app that I use regularly which is likely why this issue hasn't been resolved yet! From when I looked at this before it definitely looked like Firefox specifically was doing something a little different compared to Chromium or Thunar. I've not got any time at the moment to dig into things but I'll take a look as soon as I can and see if I work out what I need to change to get this to behave correctly.

**Comment by greweln** [comment]
@sminez Thanks for the tip. "Boxing" together  the sub -windows fixed my issue.
