### ISSUE TITLE
Penrose Project showcase proposal.

### ISSUE THREAD

**Issue by thebashpotato** [sminez/penrose#263]
I think a GitHub issue or topic similar to [the Iced project showcase](https://github.com/iced-rs/iced/issues/355) would be nice, as we could all share our Penrose built window managers.
This could help the amount of resources for new people using penrose to utilize.

**Comment by greweln** [comment]
@thebashpotato 
great suggestion!  As someone new to Penrose(and Rust in general) this would help me a lot since currently  they are very limited sources of inspiration out there.

**Comment by thebashpotato** [comment]
@greweln I went on the discord server and talked to @sminez and he would like the project showcases on the discord server as he has already dedicated a channel to it. Here is the [Discord link](https://discord.gg/jtFsg2K3Fw), see-ya there.

EDIT:
Also you should check out sminez's [Personal config](https://github.com/sminez/my-penrose-config) It's what I used to start building mine. I will posting mine in the Discord server when it's ready.

**Comment by sminez** [comment]
@thebashpotato I'm going to close out this issue in favour of the discord channel mentioned above. Happy to open it up again and pin it if people would prefer to showcase their config here in GitHub rather than discord.
