### ISSUE TITLE
Question: Are you sure file redirection can be used in `Exec=` of `Desktop Entry`

### ISSUE THREAD

**Issue by TD-Sky** [sminez/penrose#273]
In [document](https://github.com/sminez/penrose/blob/develop/docs/src/getting-started.md#making-use-of-our-new-window-manager)

```
[Desktop Entry]
Version=1.0
Name=Penrose Session
Comment=Use this session to run penrose as your desktop environment
Exec=/home/roger/my_penrose_config/target/release/my_penrose_config &> ~/.penrose.log
Icon=
Type=Application
DesktopNames=Penrose
```

I found it won't work because of [this](https://askubuntu.com/questions/1339075/how-to-redirect-the-output-from-desktop-entry).

**Comment by sminez** [comment]
Ah, I'll get that updated 👍

I'll be honest, the command shown in the docs I usually run in a script.
