### ISSUE TITLE
Allow the use of other bars e.g. polybar

### ISSUE THREAD

**Issue by griccardos** [sminez/penrose#281]
It would be awesome if penrose could support any bar, like most other window managers. 
Bars make up 80% of the awesomeness of tiling window managers in my opinion, the ability to see which workspace you're in, the active window, the stats, the icons etc. And people spend A LOT of their time setting up their favourite bar. So if they want to switch to another WM, it makes sense that they would want to bring their bar with them with the least amount of friction, and easier for them to transition to penrose.

I am new to penrose, so perhaps i missed how to use another bar. But below are the problems I faced.

Currently just running polybar does not work in penrose due to the following issues.
1) Penrose makes all docks floating but this creates a problem because all floating windows are centered (in 0.3.3)
2) bars get treated like any other window, and can gets focus when cycling windows
3) bars get a focus outline around them (when using borders)
4) they get a gap around them (when using gaps)
5) they are only on one tag at a time

what would be ideal:
Separate out bars from normal floating windows, so 
1) they get their requested position, and not centered
2) they are not included in focus cycle 
3) no focus outline 
4) no gap
5) they are included on every tag

I spent some time trying to get it it to work, and was partially successful. See video below.
But it still needs some work (does not work on multiple screens)

https://github.com/sminez/penrose/assets/30464685/656597fe-b912-48b7-b440-0396df12ecfd

You can check out my fork to see the approach i used, but generally:
- copied the way you did for floating windows: i created a `bars` hashmap in the stack set, to treat certain clients differently
- when laying out, i tested if it was a bar before allowing focus, drawing borders
- when moving tag, i moved the bar to the new tag

Some other thoughts: ideally it should automatically apply to any _NET_WM_WINDOW_TYPE_DOCK

Ideally you can guide us how you would like to approach the above, or perhaps you already have a fix.

**Comment by sminez** [comment]
Have you tried making use of the ewmh hooks extension already? That is intended for supporting the required X11 extensions to support programs like polybar. I've successfully used polybar with it in the past so I'd be surprised if polybar is completely unusable under penrose with those hooks enabled.

The approach taken by that extension is to make use of manage hooks to conditionally run additional logic when clients matching certain criteria are added to the internal window manager state. If the existing support via `ewmh hooks` doesn't meet your needs and you are able to implement something for supporting polybar as an extension (i.e. outside of the core window manager logic) using manage hooks then I'd be happy to accept a proposed design and PR so long as it didn't require modifying the existing behaviour of penrose. (Please see [the FAQs](https://github.com/sminez/penrose/blob/develop/docs/src/faq.md#wheres-the-eye-candy) for my standard answer for this sort of thing).

As a more general issue, status bars should not be stored as part of the internal stackset state: penrose is deliberately agnostic to the purpose of the windows it is managing. There are a LOT of weird and wonderful things that different X11 programs do that end up requiring hacks inside of window managers to be fully supported. My approach for penrose is to be as minimal as possible and in some cases that does end up meaning that certain things wont have full support I'm afraid.

**Comment by griccardos** [comment]
The EWMH hooks work perfectly in that the information is available to polybar (active tag number, title etc.)
I use `let config = add_ewmh_hooks(config);`

The problem more lies in that when I start polybar/eww etc. (from any terminal), it appears in the middle of the screen.
(that and the other issues noted above)

As i understand in `x /mod.rs` the `floating_client_position` sets the position to the middle of the screen. Given that all docks are considered an `AUTO_FLOAT_WINDOW_TYPES`, it gets treated like any other window. 
Am i missing something?
Should I initialize it differently, or add somethings specific, so that it appears on the top/bottom of the screen depending on the config of polybar itself?

**Comment by sminez** [comment]
Using manage hooks you should have complete control over how polybar is being treated by penrose when it spawns. That is a general purpose mechanism for handling things like this rather than status bars being treated as a special case in the core of the library.

When your hook runs you are free to position the window, manage it yourself, set X11 properties etc. I'm not entirely sure what polybar will need/expect but the setup I've got in place is based on what is provided by XMonad and I know that people have used that successfully to fully integrate polybar in the past.

**Comment by griccardos** [comment]
I will try using hooks as you suggest. 

In the meantime, running the stock standard `ewmh_compatability` example in the examples directory you have provided, the result is as per the screenshot below. Polybar is in the centre of the screen. Is that expected?
![penrose_polybar](https://github.com/sminez/penrose/assets/30464685/0d5eeca3-6300-41b4-866a-36a8e9029075)

**Comment by sminez** [comment]
@griccardos if you are using the example config from polybar itself (found [here](https://github.com/polybar/polybar/blob/master/doc/config.ini)) without any modification then yes this is expected.

https://github.com/polybar/polybar/blob/master/doc/config.ini#L65

You need to uncomment this line and set `override-redirect = true`. This is an issue with the config being given to Polybar, not an issue with Penrose. This is covered in the wiki for Polybar itself: https://github.com/polybar/polybar/wiki#i3-make-the-bar-appear-below-windows
