### ISSUE TITLE
max_char check fails in in the ActiveWindowName bar box

### ISSUE THREAD

**Issue by avery444** [sminez/penrose#295]
when the focused window title suddenly changes to something longer than the `max_chars`, it shifts the entire bar over until the end of the string. after the window title is refreshed, it fixes itself. 

the check in simple.rs succeeds if it is run from `on_refresh`, but for some reason it needs to be run in `on_event` as well.
```
if txt.chars().count() <= self.max_chars {
    self.inner.set_text(txt);
} else {
    let s: String = txt.chars().take(self.max_chars - 3).collect();
    self.inner.set_text(format!("{}...", s));
}
```
my somewhat hacky solution was to put the check in both the `on_event` and `on_refresh` functions individually and i removed the check from `set_text`.

i reproduced the bug by changing the `<title>` of a blank firefox page to something over the max char limit.

im on debian 12 and pulled the latest penrose version from git as a cargo dependency.

**Comment by sminez** [comment]
I was sure that I'd sorted this in 7b7ed7568968f2ce914952eba7ad46b0d2d259bf to be honest. Both `on_event` and `on_refresh` call through to the `set_text` method which does the truncation so I'm not following why removing the check from there and duplicating it in each method would fix this for you? Can you share the code you've ended up with please? From what you've shared so far I'm not able to make sense of why what you've proposed would result in a behaviour change unless there is something else that I'm missing.

**Comment by avery444** [comment]
i was just as confused as you were. i assumed that i had changed something, but when i tested it without any edits it did the same thing. the `altered_title` bits were to add a symbol before the text

```
struct FocusedWindow {
    text: Text,
    max_chars: usize,
}

impl FocusedWindow {
    fn new(max_chars: usize, style: TextStyle, is_greedy: bool) -> Self {
        Self {
            text: Text::new("", style, is_greedy, false),
            max_chars: max_chars.max(3),
        }
    }

    fn set_text(&mut self, txt: &str) {
        self.text.set_text(txt);
    }
}

impl<X: XConn> Widget<X> for FocusedWindow {
    fn draw(&mut self, ctx: &mut Context<'_>, s: usize, f: bool, w: u32, h: u32) -> Result<()> {
        if f {
            Widget::<X>::draw(&mut self.text, ctx, s, f, w, h)
        } else {
            ctx.fill_bg(Rect::new(0, 0, w, h))
        }
    }

    fn current_extent(&mut self, ctx: &mut Context<'_>, h: u32) -> Result<(u32, u32)> {
        Widget::<X>::current_extent(&mut self.text, ctx, h)
    }

    fn is_greedy(&self) -> bool {
        Widget::<X>::is_greedy(&self.text)
    }

    fn require_draw(&self) -> bool {
        Widget::<X>::require_draw(&self.text)
    }
    fn on_refresh(&mut self, state: &mut State<X>, x: &X) -> Result<()> {
        if let Some(id) = state.client_set.current_client() {
            let altered_title = style::TITLE_PREFIX.to_string() + &x.window_title(*id)?;
            if altered_title.chars().count() > self.max_chars {
                let s: String = altered_title.chars().take(self.max_chars - 3).collect();
                self.text.set_text(format!("{}...", s));
            } else {
                self.text.set_text(&altered_title);
            }
        } else {
            self.set_text("");
        }

        Ok(())
    }

    fn on_event(&mut self, event: &XEvent, state: &mut State<X>, x: &X) -> Result<()> {
        let name_props = [Atom::NetWmName.as_ref(), Atom::WmName.as_ref()];

        if let Some(focused) = state.client_set.current_client() {
            match event {
                XEvent::PropertyNotify(PropertyEvent { id, atom, .. })
                    if id == focused && name_props.contains(&atom.as_ref()) =>
                {
                    let altered_title = style::TITLE_PREFIX.to_string() + &x.window_title(*id)?;
                    if altered_title.chars().count() > self.max_chars {
                        let s: String = altered_title.chars().take(self.max_chars - 3).collect();
                        self.text.set_text(format!("{}...", s));
                    } else {
                        self.text.set_text(&altered_title);
                    }
                }
                _ => (),
            }
        }

        Ok(())
    }
}
```
my bar has the date at the edge of the screen, but this is what it looked like immediately after the title updated
![focused](https://github.com/sminez/penrose/assets/130318502/58549fec-d772-47f7-af08-37415b2aeef2)
and after refocusing the window
![refocused](https://github.com/sminez/penrose/assets/130318502/56d74b2f-f00f-43af-9071-81975abbdbab)

**Comment by sminez** [comment]
@avery444 I've not been able to reproduce this I'm afraid and the example code you've shown above is a modified version of what is in penrose rather than a minimal `main.rs` that can be used to demonstrate the issue.

If this is still something you are having a problem with can you please provide a minimal `main.rs` and reproduction steps for the bug?

**Comment by avery444** [comment]
sorry for the confusion. i was able to reproduce the bug using the [status bar example](https://github.com/sminez/penrose/blob/develop/examples/status_bar/main.rs) from the main repository. i've also [recorded](https://www.youtube.com/watch?v=ymUuFMfqthQ) the issue.

**Comment by sminez** [comment]
I'm afraid that running from the latest git version of penrose and attempting the same steps as you show in your video doesn't reproduce the issue for me. If you are running the `0.3.4` release rather than the head of the `develop` branch in GitHub then this would make sense as the fix was after that release. I can push a new release now so that the fix is available on crate.io but unless you're somehow running from that version rather than latest in GitHub I wouldn't expect that to change anything for you :confused: 

Can you share what your Cargo.toml looks like please?

**Comment by avery444** [comment]
i tested the minimal example with the git version and it worked as intended. i didn't think this would've been the issue because my main project is using the git version as well. i'm going to assume that i broke it in some other way, but thank you for your help!
