### ISSUE TITLE
Restart/Reload - does it exist or should it?

### ISSUE THREAD

**Issue by bbarker** [sminez/penrose#299]
In the Readme, it is stated:

> By default, Penrose is configured statically in your main.rs and compiled each time you want to make changes (similar to [Xmonad](https://www.youtube.com/watch?v=70IxjLEmomg) and [dwm](https://xmonad.org/)). There is no built-in support for hot reloading of changes or wrappers around the main window manager process.

I should probably look into how xmonad does things, since it can do hot reloads despite being statically compiled. Is there a similar means for reloading a new penrose binary without restarting all of one's apps? If not, would this be a welcome feature?

**Comment by sminez** [comment]
Hi @bbarker, if you take a look at the [run-penrose-from-scratch.sh](https://github.com/sminez/penrose-from-scratch/blob/develop/bin/run-penrose-from-scratch) script in the example window manager I built out on YouTube you can see a nice way of doing what you are after with a simple wrapper script. This is how I run penrose myself and it works really well for reloading your window manager to bring in new changes without having to log out and restart everything.
