### ISSUE TITLE
Adding more than 9 workspaces possible currently?

### ISSUE THREAD

**Issue by bbarker** [sminez/penrose#301]
Sorry if this is covered elsewhere - especially as I'm still working through the penrose-from-scratch videos on youtube. 

I've been trying to port a bit of my XMonad config over; one thing I had there was an additional 10 workspaces. 

In penrose, I did this:

```rust
        .chain(
            (["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"])
                .into_iter()
                .flat_map(|tag_base| {
                    let tag1 = format!("1{tag_base}");
                    let tag2 = tag1.clone();
                    [
                        (
                            format!("M-C-{tag_base}"),
                            modify_with(move |client_set| client_set.focus_tag(tag1.as_str())),
                        ),
                        (
                            format!("M-C-S-{tag_base}"),
                            modify_with(move |client_set| {
                                println!("DEBUG: move to {tag2}");
                                client_set.move_focused_to_tag(tag2.as_str())
                            }),
                        ),
                    ]
                }),
        )

```

I added the println to confirm the closure passed to `modify_with` is being called as expected, and it is. But the window is never moved. Similarly, M-C-{tag_base} does not move focus to a new workspace. 

This could well be buggy code on my part.

**Comment by sminez** [comment]
I'd have to see where you are specifying your default workspaces to be sure, but if you are only adding the `0` workspace here then you are creating a binding that is attempting to move clients to a workspace that doesn't exist (which would match the behaviour you are seeing).

If that's the case then you should just need to add your additional workspace tag [here](https://docs.rs/penrose/latest/penrose/core/struct.Config.html#structfield.tags).

**Comment by bbarker** [comment]
Ah yep, I'm sure that is it, so I'll close for now, and try to finish watching the videos before posting again :sweat_smile:
