### ISSUE TITLE
Request to make functions in Workspaces widget public for customization, or build in functionality

### ISSUE THREAD

**Issue by bbarker** [sminez/penrose#302]
- Is this completely new functionality, or an enhancement to existing functionality?

**Enhancement**

- What kind of feature is it that you are requesting?
  - [ ] Changes to core
  - [ ] A new layout
  - [ ] A hook implementation
  - [ ] A custom extension
  - [ ] New X interactions
  - [X] Other

### Is this a feature you have seen in other window managers?

Partly; the unicode icons I mentioned are hardcoded [in my xmonad.hs](https://github.com/bbarker/dotxmonad/blob/f17296225f61a88c39b5e0eafba86abeb48e87e8/xmonad.hs#L62-L76), but as mentioned below, I will probably aim to do something more dynamic going forward (that could be a different ticket though).

**Description:**

I was looking at extending the Workspaces widget (https://github.com/sminez/penrose/blob/develop/crates/penrose_ui/src/bar/widgets/workspaces.rs#L68) via the newtype pattern, replacing some of the functions with custom behavior. However, I realized I can't do this since many of the functions are not public. 

Would it be possible to make them public, or is the preference here to just fork the code?

---

**Context from Discord Conversation:**

---

**sminez — Yesterday at 11:50 AM**
What sort of things are you looking to do @bbarker? Depending on what it is we should hopefully be able to get something working 🙂

**bbarker — Yesterday at 12:42 PM**
I have a lot of workspaces (tags) - so I was going to add a custom filter so that only certain workspaces are displayed (e.g., workspaces with windows on them, and maybe the first and last workspace).

Also, I haven't looked into this yet in penrose, but in xmonad I was adding some unicode "icons" to certain workspaces. Before I was just doing something with hardcoding, but I may look into some mapping based on what windows or window titles are active in each workspace.

I'm mainly mentioning it just in case that influences a decision - not working on that atm.

**sminez — Yesterday at 12:46 PM**
I think exposing some extra of the internals so that you can wrap the existing workspaces widget a little easier sounds well worth looking into. Would you mind raising an issue in GitHub with the details for me? If there's any other related functionality you have from your command set that you're thinking about taking a look at it'd be worth calling that out as well.

---

Thank you for considering this request!

**Comment by sminez** [comment]
@bbarker there are a couple of ways to approach this one I think depending on what it is you are aiming to achieve.

1. The first is to do pretty much exactly what you are asking for: expose the currently internal methods as public and allow for a `Workspaces` widget to be used much like a [Text](https://docs.rs/penrose_ui/latest/penrose_ui/bar/widgets/struct.Text.html) in a new-type pattern like [this](https://github.com/sminez/penrose/blob/develop/crates/penrose_ui/src/bar/widgets/simple.rs#L141-L178).
2. Alternatively I could provide a trait that is used by the `Workspaces` widget to handle pulling together the information it needs for rendering (strings for the workspaces themselves, colours etc). That way all you need to do is provide an implementation for how you want those specific pieces of functionality to look.

The first option will give you more control but will require you to implement `Widget` yourself which is a little boilerplate-y. The second should be easier to work with but obviously the trait would need to cover the functionality you were after and users would be limited to those specific overrides. Are you able to provide a little more context over which methods you are looking to have exposed / how you are wanting to modify them please?

**Comment by bbarker** [comment]
I was basically fleshing Option 1 out and I agree it is a lot of boilerplate. Option 2 might be good for most use cases, and the question could be posed - why not both (depending on the use case).

Primarily, I'd like to be able to filter out which workspaces are shown in the bar at all using a custom filter function. Also, I might like to experiment with drawing extra unicode symbols next to the workspace # using either a hardcoded value, or more ideally, a function that inspects the workspace and what apps are running on it. So maybe I'd draw 6[ :crab: :globe_with_meridians: ] If I had an editor with rust running and a web browser on workspace 6. This latter isn't a hard requirement for me, but I think it would be cool to do, though likely not always perfect (e.g., detecting Rust files in an editor)

From reading, it looks like `current_extent` and `draw` could be the primary functions I'd need to be able to change for this. But having a `tag_map` function that can access workspace data (window info) and have `current_extent` and `draw` use that might satisfy the extra unicode character requirement, and similarly, having a `tags_filtered` function that  `current_extent` and `draw` use would satisfy the first requirement of only drawing some tags; in both cases the default for these would just be to do the current behavior (`tag_map` would just return the tags as they are, and `tags_filtered` wouldn't actually do any filtering).

**Comment by sminez** [comment]
@bbarker I've put together a first pass at this (but not had a chance to test it out yet) if you are interested in taking a look? https://github.com/sminez/penrose/compare/issue-302?expand=1

**Comment by sminez** [comment]
closed by #309
