### ISSUE TITLE
Add `is_floating` to `StackSet`.

### ISSUE THREAD

**Issue by codybloemhard** [sminez/penrose#306]
### Please describe the change / addition you'd like to see made

I was digging through the docs and looking at the source of some methods to find out if I could figure out if a specific window is currently floating or not. I could not find it. Excuse me if I missed something.

This would give users the ability to toggle floating windows.
All it would require is to add this to `StackSet`:

```rust
pub fn is_floating(&mut self, client: &C) -> bool {
    self.floating.contains_key(client)
}
```

With that, I can write an action like this (not final):

```rust
pub fn toggle_float_focused<X: XConn>() -> Box<dyn KeyEventHandler<X>> {
    key_handler(|state, x: &X| {
        let id = match state.client_set.current_client() {
            Some(&id) => id,
            None => return Ok(()),
        };

        let r = x.client_geometry(id)?;

        x.modify_and_refresh(state, |cs| {
            if cs.is_floating(&id) {
                cs.sink(&id);
            } else if let Err(err) = cs.float(id, r) {
                // if this action where to be included in penrose
                // error!(%err, %id, "unable to float requested client window");
            }
        })
    })
}
```

I can open a pull request if this functionality is desirable.

- Is this completely new functionality, or an enhancement to existing functionality?

Just enhancing the existing code for dealing with floating windows.

- What kind of feature is it that you are requesting?
  - [x] Changes to core
  - [ ] A new layout
  - [ ] A hook implementation
  - [x] A custom extension
  - [ ] New X interactions
  - [ ] Other

### Is this a feature you have seen in other window managers?

i3 does have a floating toggle (eg. `bindsym $mod+Shift+f floating toggle`).

**Comment by sminez** [comment]
I'd be happy to get this added if you are up for writing the PR @codybloemhard? I think it should also include `toggle_floating` (or maybe `toggle_floating_state`?) as a method directly on `StackSet` rather than users having to write the conditional behaviour themselves.
