### ISSUE TITLE
Add link to docs

### ISSUE THREAD

**Issue by timuric** [sminez/penrose#308]
It would be easier to discover docs if the repo info would include link to https://sminez.github.io/penrose/

**Comment by sminez** [comment]
The [tl;dr - getting started](https://github.com/sminez/penrose?tab=readme-ov-file#tldr---getting-started) section of the readme has a link to the docs currently. Are you meaning adding it to the "About" section that GitHub shows in the top right?

**Comment by timuric** [comment]
@sminez yep

**Comment by sminez** [comment]
Done :slightly_smiling_face:
