### ISSUE TITLE
Borderless Fullscreen not working

### ISSUE THREAD

**Issue by PraneethJain** [sminez/penrose#312]
### Describe the bug

The `toggle_fullscreen` extension does not remove the borders when going into fullscreen.

### To Reproduce

- https://github.com/PraneethJain/wm/tree/borderless-fullscreen (You will need to change the hardcoded wallpaper path)
- Press `M-f` to toggle_fullscreen

### Expected behavior
- The border should not be visible when in fullscreen mode

### Screenshots

![image](https://github.com/user-attachments/assets/b536c164-a40a-44a5-8b0e-0c590310a020)
The border is visible even after `toggle_fullscreen` is called.

### Versions & OS Details
- OS: Linux
- Distribution: Void
- Penrose Version: 0.3.6

### Additional context

- [x] minimal main.rs that reproduces the issue
- [ ] debug log output

**Comment by sminez** [comment]
Hi @PraneethJain :wave:

Sorry about the delay on addressing this one. I've tested this out locally and this all works fine for me when explicitly setting a client window to fullscreen and back using the `toggle_fullscreen` action but as I mentioned on Discord, I don't think my handling of Fullscreen client messages being sent by clients themselves is currently correct so I'll take a look at that as well.

**Comment by PraneethJain** [comment]
Hi @sminez, thanks for the fix. There seems to be another problem though.

On going fullscreen, there is a gap on the bottom and right side of the screen from where I can see my wallpaper?
![image](https://github.com/user-attachments/assets/591cda7f-4f09-4c3d-b2b8-6e37109e96ec)

**Comment by sminez** [comment]
Yeah I'd just noticed that as well. I've pushed a fix for that now if you're ok to try it? The issue was that the positioning logic for making the API calls to the X server unconditionally shrinks all client positions according to the configured border width.

https://github.com/sminez/penrose/commit/a0f3669282bfb8a0eb926addc8187513fcfdab6d

**Comment by PraneethJain** [comment]
Works now, thanks!
