### ISSUE TITLE
dwm style tags extension

### ISSUE THREAD

**Issue by sminez** [sminez/penrose#32]
Using the existing hook points, it should be possible to implement a dwm style tags system instead of the default workspaces. This would require tracking the active tags for each window (defaulting to a single tag) and intercepting workspace switching to ensure that the correct windows were visible at all times. I'm not sure if the current `Workspaces` status bar widget would be able to handle displaying the active tags in the same way as the built in dwm bar but a modified widget should be possible.

**Comment by Armavica** [comment]
Hello, I am interested in this feature but I don't understand why the issue is closed: has it been implemented or has it been decided that it will not be implemented?

**Comment by sminez** [comment]
If I remember correctly, it was closed because it turned out that it would actually be a fair amount of work to get working correctly. (Sorry, should have posted the details here when I closed it...)

The idea that clients are on a single workspace is pretty deeply engrained into the way that Penrose works. One option would be to only have two `Workspaces` (visible and non-visible) and then to build a tagging system that sat on top of that. You'd need to write your own helpers for managing "moving" or tagging clients and anything that expected the workspace model (such as the status bar widgets).

It's definitely doable but it's a fair amount of work and mostly likely would result in some "interesting" behaviour when combined with other extensions...

If you are interested I can take a look at writing up a spec at the weekend?

**Comment by Armavica** [comment]
Thank your for your answer! I am coming from dwm and I have the tags system deeply rooted both in paradigm and muscle memory… However I want to give a go to the workspaces approach before trying to implement this, especially if it is so complex to implement. So I might ask you later again about this if I don't managed to get used to workspaces…

**Comment by sminez** [comment]
Sounds good :+1:
