### ISSUE TITLE
handle mouse events

### ISSUE THREAD

**Issue by sminez** [sminez/penrose#36]
penrose doesn't currently listen to any mouse events which blocks things like floating mode and click to focus. The window manager needs to take action based on user key bindings for at least:

- [ ] reposition client
- [ ] resize client

Click to focus would be nice as well but that is tied up with disabling focus follow mouse and all of the edge cases that come with that so it is probably best left for another issue.

**Comment by pr2502** [comment]
Hi, I'm looking into this as it's a blocker for me to switch from i3 to penrose.

Do you have any design in mind I should try and implement or should I just experiment and get back to you when I get a prototype working?

**Comment by sminez** [comment]
Hi @ametisf , I started looking into this one last night actually: I haven't got too much of a design nailed down yet other than initially aiming to replicate `dwm` functionality and then iterate from there. If you have any specific needs not covered by the initial description above it would be good to hear them actually: rough initial plan is to get event click positions getting passed through to the main `WindowManager` event loop along with the id of the window containing the click (pretty sure the xcb event API gives us this for free). From there it's a case of adding methods that can be bound by the user I suppose: resize and reposition being the main ones, both of which need to be aware of the current layout. I was going to go for "if you resize or reposition a window, you pop it out of the current layout and make it floating" but that'll need some additional state management I suspect as workspaces don't currently understand floating windows as belonging to a particular workspace.

**Comment by pr2502** [comment]
Thanks for your response.

As you wrote xcb gives us the positions for free, and passing those on was just a few lines in `core/xconnection.rs`

```
xcb::MOTION_NOTIFY => {
    let e: &xcb::MotionNotifyEvent = unsafe { xcb::cast_event(&event) };
    Some(XEvent::MotionNotify {
        id: e.event(),
        rpt: Point::new(e.root_x() as u32, e.root_y() as u32),
        wpt: Point::new(e.event_x() as u32, e.event_y() as u32),
    })
}
```

As far as I understand dwm doesn't let users manually change window's floating state (except the floating layout).

My idea was to replicate what i3 does. Add another `Ring<Client>` into `Workspace` and track tiled and floating windows separately with a function to switch the floating state (from the layout functions perspective floating windows don't exist) and another function to toggle focus between the focused tiled window and focused floating window (with `cycle_client` working both on tiled windows and floating windows depending on which are in focus). The i3 controls which I'm used to are mod+leftclick+drag to move floating windows and mod+rightclick+drag to resize floating windows freely and resize containers when sharing a border with other container (this might be mappable to main ratio in penrose?).

**Comment by sminez** [comment]
all sounds good to me 👍 if you have started work on this already, do you want to take a stab at it and get a prototype together? If you're happy to do so, breaking this into a couple of PRs would be really helpful (i.e. surfacing the events through to `WindowManager`, allowing clients to respect the new triggers / state, adding the `pub fn` methods for use in config etc)

**Comment by pr2502** [comment]
Absolutely, I've already started playing with it a bit. I'll open a PR when it starts doing something and then let you decide how to split it up, I'm still a bit confused about the overall architecture so it will probably require a few revisions.

**Comment by sminez** [comment]
No worries: I should try to put together an overview of how everything fits together so that it's easier for people to get their heads round.

**Comment by pr2502** [comment]
So far I've added the events and modified the `Workspace` structure to use the two layers. Now I'm reading through i3 codebase to figure out how are they handling the the continuous repositioning/resizing of windows during the dragging action.

I have a few questions:

1. Is there a way for me to get window's current dimensions you happen to know of? i3 is tracking this info themselves, `xcb::get_geometry` nor `xcb::get_property` don't seem useful and I'm unable to find any other way to get it with xcb. Otherwise I'll track them myself too.
2. What is the purpose of the `focused_client` field in `WindowManager`? I'm really not sure how I should use it, I'd personaly prefer to remove it if it's just for caching the `WinId`.
3. `client_lost_focus` is called by `client_gained_focus`, however most (all?) places calling `client_gained_focus` also call `client_lost_focus` themselves which is redundant and may cause issues if/when it stops being idempotent. I'm not sure whether I should call the function or not.

**Comment by sminez** [comment]
In response to your numbered questions:
1) There _is_ a way to get the current window dimensions yeah: [get_geometry](https://www.mankier.com/3/xcb_get_geometry). In the crate I'm using it should be `xcb::xproto::get_geometry` I think.
2) `focused_client` is there because the currently focused client is not always tied to a particular workspace (for example it might be a scratchpad) which leads either to odd behaviour a lot of double checking things if we don't track it. Please do not remove it.
3) Unless I'm wrong, I see `client_lost_focus` being called in `handle_enter_notify` (not needed), `handle_leave_notify` (needed) and `cycle_client` (_maybe_ needed...). In the `cycle_client` case it should be fine to not explicitly call `client_lost_focus` on what the workspace considers to be the previously focused client, but this was added due to some odd behaviour that could arise with cycling clients. I'll take a look and see, but hopefully that one is redundant as well.

Regarding splitting clients into the two layers, please can you add test cases for how this is handled when changing workspaces, moving workspaces between screens and moving clients between workspaces / screens. All of these going to have to deal with this new state and it may break a few things if we're not careful.

With that in mind, It might be easier to keep the single clients `Ring` and instead, have the methods on `Workspace` switch their behaviour based on the state of the focused client (e.g. if the focused client is floating then we're cycling through floating clients only). Either way, I'd prefer it if you could raise a PR with this change first so I can see how you are approaching the problem: it feels like there are going to be a lot of places where this could bump up against assumptions made in the main `WindowManager` code!

**Comment by pr2502** [comment]
Ad 1. again, what is "current window" in xcb naming scheme? Is there some way to set a "current window"? I thought it only works for normal clients which have their own window, not for a window manager.

Ok, I'll make the PR now, it doesn't really do anything at all yet (since I'm still missing a lot of intermediary functionality) but it'll at least help as a context for any possible questions.

**Comment by sminez** [comment]
Ah sorry, that function is for a specific window id I think. Details should be in the documentation that I linked to.
