### ISSUE TITLE
changing the order that windows are added

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#39]
**Is your feature request related to a problem? Please describe.**
My current work flow is that I tend to have a main window open and then open secondary windows for running compiles or reading documentation.

It appears that this is not possible at present with penrose unless it can be done using an add/remove hook

**Describe the solution you'd like**
The ideal would be a simple flag that I could set that would cover the adding and removal of windows

**Describe alternatives you've considered**
Using a hook to do this would be fine if there was an example of how this would work

**Additional context**
At hne moment I am loving the look of penrose and it covers most of the things that I was intending putting into the window manager that I started. The only thing missing other than the above would be the ability to change some internal viarables aka bspwm but that is just a thing that would be nice rather than anything that is really needed

**Comment by sminez** [comment]
I'm afraid I don't understand what it is that you are asking for here...
The example configs show multiple ways of opening new programs (the run_external macro, the spawn function or spawning a helper such as dmenu).

Can you please explain what it is you feel Penrose is missing?

"Change some internal viarables aka bspwm"

Again, I'm not sure what you mean here. Can you please give an example?

**Comment by crypt17** [comment]
The main issue that I have is that if I have two terminals open and focused
on the first one then when I open the new terminal it takes the master
location whereas I would like it to take the next location.

eg if I have windows
1,2,3 antd window 2 has focus I would like to have 1,2,4,3 vs 4,1,2,3 as
happens now

As for the bspwm example I have found it useful recently to be able to do
things like change workspace names on the fly using bspc.

**Comment by sminez** [comment]
Changing workspace names on the fly is possible and yes will require using a hook (Penrose does not follow the bspwm client/server model).

You should be able to write an extension method using the **new_client** and **event_handled** hooks to cause clients to insert after the focused client instead of at the head position. This is the intended method for adding this sort of new functionality to Penrose.

**Comment by crypt17** [comment]
cool I will have a look at the new_client hook. Is that the add_client,
remove_client hooks?

**Comment by sminez** [comment]
Ah sorry! Yes those are the ones :smile:

You probably want to do something similar to how the status bar works where you catch that a client has been spawned using **new_client** and then reposition it in **event_handled** in order to let Penrose add it to workspace and map the window first.

You might end up wanting to write a new WindowManager method for simply specifying an order for clients on a workspace rather than repeatedly calling the drag_client method.

**Comment by crypt17** [comment]
thanks I will have a look at that.The one issue I had with the hook to do
this sort of thing in xmonad was that when a window was.closed it would
always focus the wrong window as there was no on close hook.

The more I look at penrose the more I find it has the things that I have
been wanting in a window manager.

**Comment by sminez** [comment]
Hi @crypt17 , I took a look at this this morning and on second thought, I think you are right that this should be something native to the window manager itself as opposed to having to implement this via hooks. In https://github.com/sminez/penrose/commit/e0ea69355ae3a20d66c333e7af5c0a43bdb4c915 I have added the option for specifying an insert point to be used when adding new clients, defaulting to the current behaviour of inserting at index 0. I'm closing this issue for now but please do let me know if there are any issues with this for your use case.

**Comment by crypt17** [comment]
wow that was fast. I was just tinkering with some code for this yesterday.
I will have a look at your code more later today

**Comment by crypt17** [comment]
I jst had a look at your addition and thought that the following addition
might add an extra useful option

diff --git a/src/core/data_types.rs b/src/core/data_types.rs
index 563e88c..c93eb81 100644
--- a/src/core/data_types.rs
+++ b/src/core/data_types.rs
@@ -131,6 +131,8 @@ pub enum InsertPoint {
     Index(usize),
     /// In place of the current focused element (pushing focused and later
down in the stack)
     Focused,
+    /// after the focused element
+    After,
     /// As the first element in the stack
     First,
     /// As the last element in the stack
@@ -295,6 +297,7 @@ impl<T> Ring<T> {
         match insert_point {
             InsertPoint::Index(ix) => self.elements.insert(*ix, element),
             InsertPoint::Focused =>
self.elements.insert(self.focused_index(), element),
+            InsertPoint::After =>
self.elements.insert(self.focused_index()+1, element),
             InsertPoint::First => self.elements.push_front(element),
             InsertPoint::Last => self.elements.push_back(element),
         }

This simply adds the window after the currently focused one.

**Comment by sminez** [comment]
Hi @crypt17 , thanks for the suggestion. It needs a little bit of a tweak to avoid panicing if the index is out of bounds but this is now pushed as of 21667d9009bcfb8dade40e46b608db3b8e480988

```diff
diff --git a/src/core/data_types.rs b/src/core/data_types.rs
index 563e88c..5ed8a0f 100644
--- a/src/core/data_types.rs
+++ b/src/core/data_types.rs
@@ -131,6 +131,8 @@ pub enum InsertPoint {
     Index(usize),
     /// In place of the current focused element (pushing focused and later down in the stack)
     Focused,
+    /// After the current focused element (pushing later elements down in the stack)
+    AfterFocused,
     /// As the first element in the stack
     First,
     /// As the last element in the stack
@@ -297,6 +299,14 @@ impl<T> Ring<T> {
             InsertPoint::Focused => self.elements.insert(self.focused_index(), element),
             InsertPoint::First => self.elements.push_front(element),
             InsertPoint::Last => self.elements.push_back(element),
+            InsertPoint::AfterFocused => {
+                let ix = self.focused_index() + 1;
+                if ix > self.elements.len() {
+                    self.elements.push_back(element)
+                } else {
+                    self.elements.insert(ix, element)
+                }
+            }
         }
     }

@@ -631,5 +641,10 @@ mod tests {
         r.focus(&Selector::Index(1));
         r.insert_at(&InsertPoint::Focused, 4);
         assert_eq!(r.as_vec(), vec![1, 4, 0, 0, 3, 2]);
+        r.insert_at(&InsertPoint::AfterFocused, 5);
+        assert_eq!(r.as_vec(), vec![1, 4, 5, 0, 0, 3, 2]);
+        r.focus(&Selector::Index(6));
+        r.insert_at(&InsertPoint::AfterFocused, 6);
+        assert_eq!(r.as_vec(), vec![1, 4, 5, 0, 0, 3, 2, 6]);
     }
 }
```

**Comment by crypt17** [comment]
nice.

My original reading of.the docs seemed to indicate that if the index was
out of bounds then it was converted to an append at the lower layer.
