### ISSUE TITLE
Make "xconnection" a feature

### ISSUE THREAD

**Issue by cshao06** [sminez/penrose#40]
**Is your feature request related to a problem? Please describe.**
I was trying to reuse the xconnection module and define my own WindowMangager struct. I wish the xconnection module could be a standalone feature so that I don't need to compile everything else in the penrose crate.

**Describe the solution you'd like**
Make xconnection a feature that could be specified in dependencies in Cargo.toml.

**Describe alternatives you've considered**
Copy the xconnection module to my local package

**Additional context**
It'd be nice to make the crate more modular. Please let me know if you think it would make sense to use only the xconnection module. I'm also not sure if making it a feature is the best way.

**Comment by sminez** [comment]
The XConn trait is the only part of the xconnection module that is supported as a public API. The xcbconnection struct (which is what I assume you are referring to) implementation detail of Penrose that is not stable. It is undergoing frequent rewriting as I get Penrose to a state that I am happy with and is not fit for use in other crates.

Please do feel free to copy / reuse any of the code contained in the module, but I'm afraid it is not going to be exposed as it's own crate. At least not until it is more stable as I don't have the time or ability to support it in that fashion.
