### ISSUE TITLE
out of bounds exception draw example

### ISSUE THREAD

**Issue by waidmann06** [sminez/penrose#45]
Using examples draw.rs throws "index is put of bounds: the Len is 0 but the index is 0, src/draw/bar/widget.rs:237:12
-

**Comment by sminez** [comment]
ah, thanks! sorry about that: the status bar now expects to be initialised via a startup hook fired by the window manager. This example doesn't actually run the window manager itself so it needs to be triggered manually: fix is in e3c0fefae2221835427a4c4ec1c3888195a2433f

**Comment by waidmann06** [comment]
no need to apologise, thanks a lot. Love the project
