### ISSUE TITLE
Client window not mapped correctly after being moved to another workspace.

### ISSUE THREAD

**Issue by Danacus** [sminez/penrose#46]
**Describe the bug**
When moving a client to an undisplayed workspace the client will not be mapped and its window will be invisible when switching to said workspace for the first time.

**To Reproduce**
1. Create a new client
2. Move the client to another workspace (`client_to_workspace`)
3. Focus the workspace the client was moved to (`focus_workspace`)
4. The client is not visible

**Expected behavior**
I would expect the client to become visible when switching to its workspace.

**Desktop**
 - OS: Linux
 - Distribution Arch Linux

**Additional context**
I might have already found a solution. The `client_to_workspace` function calls `XConn.unmap_window`, however this causes `Client.mapped` to remain `true`.  
This is the code I'm talking about: https://github.com/sminez/penrose/blob/21667d9009bcfb8dade40e46b608db3b8e480988/src/core/manager.rs#L675-L706  
Replacing `self.conn.unmap_window(id);` with `self.unmap_window_if_needed(id);` (near the bottom of this method) solves the issue for me. This way `Client.mapped` will be set to `false`.

Let me know if you want me to create a PR with this solution or if you prefer fixing this yourself.

**Comment by sminez** [comment]
ah thanks, this is an oversight from implementing the full screen client support. There's actually multiple places that need updating due to this. I'll push a fix now.

**Comment by sminez** [comment]
fix is in ceacaaf624ecc26ba753a4eb551b31f2031a374b
