### ISSUE TITLE
Is it like Xmonad in terms of how configuration is done?

### ISSUE THREAD

**Issue by Joe23232** [sminez/penrose#50]
I am thinking about giving `penrose` a try. But I have a few questions regarding this project.

1. Is it like XMonad where the user has the source code with them and they use a main file to code the tiling Window Manager in an empty file in a high level manner?
2. Is it possible to add window decorations, just like with `awesome` WM?
![Full window](https://user-images.githubusercontent.com/34926497/92197064-10b45880-eeb4-11ea-8f14-e4eca44a832d.png)
3. Is it possible to add round corners around the windows?
4. Does it come with other stuff such as a taskbar?
5. Is it as easy to script `penrose` as it is with XMonad?

**Comment by sminez** [comment]
Please take a look at the example configs in the "examples" directory and details in the readme for how to configure Penrose.

No it is not possible to add decorations or rounded corners.

**Comment by Joe23232** [comment]
Oh would this be implemented in the near future though the rounded corners and decorations?
