### ISSUE TITLE
Key input not captured when numlock is enabled.

### ISSUE THREAD

**Issue by Danacus** [sminez/penrose#51]
**Describe the bug**
Whenever numlock is enabled, penrose stops capturing key events.

**To Reproduce**
1. Enable numlock
2. Try to use any configured key binding
3. Observe that penrose ignores the key event and it will be passed to the focused client

**Expected behavior**
I expected penrose to respond to these key events regardless of whether numlock is enabled.

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution Arch Linux

**Additional context**
- The minimal example can be used to reproduce the issue.
- Here is the log where enabled numlock and pressed several keybinds. None of those are shown in the log. The only one it outputs is the exit keybind after I disabled numlock. [penrose log](https://gist.github.com/Danacus/d47d35e0fc3ae22c527e9d0f87f9b191)
- [xmodmap -pke](https://gist.github.com/Danacus/dff2f9a895a74d1cf38d43f816a4d518)

Do you know why this might be happening? I'll do some more debugging and post more information if I find something.

**Comment by sminez** [comment]
I suspect that NumLock will be getting flagged as a modifier key. If you run with debug output can you post the logged key events both with and without NumLock on please?

**Comment by Danacus** [comment]
Without numlock:

```
07:29:37 [INFO] updating known screens: 1 screens detected
07:29:37 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 1600, h: 900 }, effective_region: Region { x: 0, y: 18, w: 1600, h: 882 } }
07:29:37 [DEBUG] (1) penrose::core::manager: got XEvent: RandrNotify
07:29:37 [INFO] updating known screens: 1 screens detected
07:29:37 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 1600, h: 900 }, effective_region: Region { x: 0, y: 18, w: 1600, h: 882 } }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: KeyPress { code: KeyCode { mask: 64, code: 36 } }
07:29:43 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 64, code: 36 }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 4194306 }
07:29:43 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 4194306
07:29:43 [WARN] attempt to remove unknown client 4194306
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: MapRequest { id: 4194311, ignore: false }
07:29:43 [INFO] new client with WM_CLASS='Alacritty'
07:29:43 [DEBUG] (1) penrose::core::workspace: applying '[side]' layout for 1 clients on workspace '1'
07:29:43 [DEBUG] (1) penrose::core::manager: configuring 4194311 with Some(Region { x: 0, y: 18, w: 1600, h: 882 })
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 4194311, atom: "_NET_WM_DESKTOP", is_root: false }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 4194311, r: Region { x: 5, y: 23, w: 1586, h: 868 }, is_root: false }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: Enter { id: 4194311, rpt: Point { x: 800, y: 459 }, wpt: Point { x: 793, y: 434 } }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 4194311, atom: "WM_HINTS", is_root: false }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 4194311, atom: "WM_NAME", is_root: false }
07:29:43 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 4194311, atom: "_NET_WM_NAME", is_root: false }
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: KeyPress { code: KeyCode { mask: 64, code: 11 } }
07:29:44 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 64, code: 11 }
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: Leave { id: 4194311, rpt: Point { x: 800, y: 459 }, wpt: Point { x: 793, y: 434 } }
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: KeyPress { code: KeyCode { mask: 64, code: 10 } }
07:29:44 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 64, code: 10 }
07:29:44 [DEBUG] (1) penrose::core::workspace: applying '[side]' layout for 1 clients on workspace '1'
07:29:44 [DEBUG] (1) penrose::core::manager: configuring 4194311 with Some(Region { x: 0, y: 18, w: 1600, h: 882 })
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: Enter { id: 4194311, rpt: Point { x: 800, y: 459 }, wpt: Point { x: 793, y: 434 } }
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: ConfigureNotify { id: 4194311, r: Region { x: 5, y: 23, w: 1586, h: 868 }, is_root: false }
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 4194311, atom: "WM_HINTS", is_root: false }
07:29:44 [DEBUG] (1) penrose::core::manager: got XEvent: PropertyNotify { id: 4194311, atom: "WM_HINTS", is_root: false }
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: KeyPress { code: KeyCode { mask: 65, code: 24 } }
07:29:45 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 65, code: 24 }
07:29:45 [DEBUG] (1) penrose::core::manager: removing ref to client 4194311 (Alacritty)
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 6291456 }
07:29:45 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 6291456
07:29:45 [WARN] attempt to remove unknown client 6291456
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 10485760 }
07:29:45 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 10485760
07:29:45 [WARN] attempt to remove unknown client 10485760
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 12582912 }
07:29:45 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 12582912
07:29:45 [WARN] attempt to remove unknown client 12582912
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 8388608 }
07:29:45 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 8388608
07:29:45 [WARN] attempt to remove unknown client 8388608
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: Leave { id: 4194311, rpt: Point { x: 800, y: 459 }, wpt: Point { x: 793, y: 434 } }
07:29:45 [DEBUG] (1) penrose::core::manager: got XEvent: Destroy { id: 4194311 }
07:29:45 [DEBUG] (1) penrose::core::manager: DESTROY_NOTIFY for 4194311
07:29:45 [WARN] attempt to remove unknown client 4194311
07:29:46 [DEBUG] (1) penrose::core::manager: got XEvent: KeyPress { code: KeyCode { mask: 72, code: 9 } }
07:29:46 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 72, code: 9 }
```

With numlock:

```
07:30:32 [INFO] updating known screens: 1 screens detected
07:30:32 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 1600, h: 900 }, effective_region: Region { x: 0, y: 18, w: 1600, h: 882 } }
07:30:32 [DEBUG] (1) penrose::core::manager: got XEvent: RandrNotify
07:30:32 [INFO] updating known screens: 1 screens detected
07:30:32 [INFO] screen (0) :: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 1600, h: 900 }, effective_region: Region { x: 0, y: 18, w: 1600, h: 882 } }
```

In both cases I pressed the same keys. None of the keys are logged when numlock is enabled. You are probably right about Num_Lock getting flagged as modifier key. I will try to make some quick changes to allow registering Num_Lock as modifier to a keybind to confirm whether this is the case.

**Comment by Danacus** [comment]
I figured it out, you were right about it being a modifier. Numlock is `MOD_MASK_2`. I tested this by adding it to the match expression in `parse_key_binding`:

```
&"A" => xcb::MOD_MASK_1,
&"M" => xcb::MOD_MASK_4,
&"S" => xcb::MOD_MASK_SHIFT,
&"C" => xcb::MOD_MASK_CONTROL,
&"N" => xcb::MOD_MASK_2,
&_ => panic!("invalid key binding prefix: {}", s),
```

If I would duplicate every keybinding in my config like this, it will work as expected.

```
"M-Return" => run_external!(my_terminal),
"N-M-Return" => run_external!(my_terminal),
```

This is obviously not a great solution. (but it could have it's uses, as it essentially gives you twice the amount of available keys to choose from! :smile: )

**Comment by sminez** [comment]
Ah, yeah that's not ideal...! If numlock is _always_ **MOD_MASK_2** then we should be able to explicitly remove it from the mask but I'd like to confirm that this is the case otherwise we'd be risking dropping valid modifiers for some users.

**Comment by Danacus** [comment]
I appears like it's _usually_ the case. However there might be exceptions. `xmodmap -pm` will show all modifiers.

```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

I think num lock wil always me called `Num_Lock` here, but it could theoretically be another modifier than `mod2`. It might be better to figure out which modifier corresponds to `Num_Lock`, but that might be harder to implement.

**Comment by Danacus** [comment]
I took a quick look at dwm and this is their solution:

First they figure out which modifier corresponds to `Num_Lock`. Then they will loop through all key bindings just like penrose, but instead of grabbing a single key with a single set of modifiers for each keybind, they will run `grab_key` with each of the following masks added one at a time:

`unsigned int modifiers[] = { 0, LockMask, numlockmask, numlockmask|LockMask }`

For reference, this is the code I'm looking at: [dwm.c](https://git.suckless.org/dwm/file/dwm.c.html#l949).

I'm pretty sure this could work for penrose too. We could figure out which modifier is `Num_Lock` using `xmodmap -pm` or [`xcb::xproto::get_modifier_mapping`](https://docs.rs/xcb/0.9.0/xcb/xproto/fn.get_modifier_mapping.html) (we should probably deal with `Caps_Lock` too, it has the same problem). Then in `XConn.grab_keys` we could loop over each ignored modifier combination for every key we want to grab.

Do you think this would be a good solution or do you have a better idea?

**Comment by sminez** [comment]
I was taking a look at the dwm code for this earlier as well actually: I think this is probably the simplest way to go on this one. When we are processing the key events as they come in we can mask out the additional modifiers so that we ignore them: that way we don't end up with a **4x** increase on the keybindings map and when we pass our `XEvent` back to the `WindowManager`, we only ever talk about things in terms of the original bindings.

**Comment by Danacus** [comment]
Okay I think I understand what you mean, I didn't even consider that. It explains why some of my experiments didn't work. I tried adding an additional mask in `grab_keys` but it didn't work because the key map wasn't changed accordingly, so the events were ignored by `WindowManager`. 

I agree that ignoring these modifiers when receiving events is better than having 4 times as much keybinds.

**Comment by Danacus** [comment]
I made a very rough implementation: [commit](https://github.com/Danacus/penrose/commit/26a78c5acb14e42b9069e924fba254cce7d34f0a).

I've created a constant with all combinations of ignored modifiers for grabbing keys and another constant with the combined mask that's used for ignoring modifiers in key events (`mask: k.state() & !ignored_mask`).

But it assumes that `Num_Lock` is always `MOD_2`, which might not be the case in rare cases. It might also be weird to send the mask as an argument to `KeyCode::from_key_press`, but besides that it works as expected.

**Comment by sminez** [comment]
As a general aproach that looks OK I think though you probably want to do something like dwm's `updatenumlockmask` in order to ensure that you are using the correct value. As for passing the mask to `from_key_press`, I agree that it's a little odd. Maybe keep that function as it is but add a method to apply the mask? For the mouse binding stuff I'm working on now (#49) I suspect I'm going to need to use the same logic but it might still be useful to create a keybinding without a mask an not have to worry about what value to pass. (That or make it an option I suppose?)

**Comment by Danacus** [comment]
I've made some more [progress](https://github.com/Danacus/penrose/commit/de1db63fe13fbbeb7d74ba4690fd1127a39beb80). 

What I did is implement functions to turn something like `&["Num_Lock", "Caps_Lock"]` into 

```rust
vec![
    0,
    xcb::MOD_MASK_2 as u16,
    xcb::MOD_MASK_LOCK as u16,
    (xcb::MOD_MASK_2 | xcb::MOD_MASK_LOCK) as u16,
];
```

But the code for doing this power set thing looks like black magic (based on [this](https://www.geeksforgeeks.org/power-set/)) and is probably overkill for this use case, so I might get rid of it. Once we have this vector, finding the total combined mask (used in `wait_for_event`) is as simple as getting the largest number from the vector. I've also stored this vector in `XcbConnection`, but I'm not sure if this is the best solution. I'll let you decide.

**Comment by sminez** [comment]
You shouldn't need to do anything with different from the logic in dwm as far as working out which modifiers to grab goes I wouldn't of thought. The powerset idea is just taking all possible combinations of the various masks I assume? If so, that sounds like what we _probably_ need, but again: I'd defer to the implementation in dwm on this one.
I'm not sure by what you mean by "total combined mask" especially if it's something you are arriving at by taking the highest integer valued mask that you've found in this powerset. I would have expected it to be the bitwise OR of all the masks we're ignoring (which may well be the case from what you are saying but that should be clear in the code I think). I'd have expected that we then mask off (i.e. set to 0) this set of ignored modifiers on the raw event we receive before attempting to find it in our known keybindings.

In terms of storing these masks, yes we should most likely be storing them on inside of `XcbConnection` (as this is _definitely_ an implementation detail) but we probably need to be able to cope with the modifiers being updated. That sounds like a non-trivial extension of this initial idea so it might be worth getting the logic in place specifically for `NumLock`, getting that in a state that is able to be merged and then raise an issue to spec out what would need to be done to go further.

**Comment by Danacus** [comment]
> The powerset idea is just taking all possible combinations of the various masks I assume?

Yes, it is.

> I would have expected it to be the bitwise OR of all the masks we're ignoring (which may well be the case from what you are saying but that should be clear in the code I think)

Exactly, but I agree that it isn't clear from the code and my variables could be named better.

> I'd have expected that we then mask off (i.e. set to 0) this set of ignored modifiers on the raw event we receive before attempting to find it in our known keybindings.

Yes, that's how it works. 

> [...] it might be worth getting the logic in place specifically for NumLock, getting that in a state that is able to be merged and then raise an issue to spec out what would need to be done to go further.

That might be a better approach.

**Comment by Danacus** [comment]
Looking at `dwm` source code I found that we probably don't have to worry about modifiers being updated at runtime. `dwm` only updates the mask every time it grabs keys. `penrose` currently does not implement grabbing keys on `xcb::MAPPING_NOTIFY`, but that's a different potential issue.

The point is that we only need to update the modifiers whenever we grab keys, which is currently only once, so I did it at the creation of `XcbConnection`.

**Comment by sminez** [comment]
@Danacus I merged your PR earlier and I've just had a look at verifying it all locally. In doing so I realised that you seem to be ignoring the actual keycodes returned from `xmodmap` (and the Keys that are assigned to each modifier) which means that your helper function is always returning the same map from what I can see. With that in mind, it might be best to just hard code the use of `xcb::MOD_MASK_2` where we need it.

**Comment by Danacus** [comment]
It might be easier indeed, especially since it's now the responsibility of the person configuring `penrose`. They can figure out by themselves that they want to use `MOD_MASK_2` for `Num_Lock` or if it happens to be a different mask on their system for some reason. The `xmodmap` function was meant for figuring out which modifier mask corresponds to the key named `Num_Lock` so we wouldn't have to guess that it's `MOD_MASK_2` like it usually is, but it's no longer that useful now. So it might be better to just get rid of that abomination of a function I wrote :)
