### ISSUE TITLE
Bar transparency

### ISSUE THREAD

**Issue by Danacus** [sminez/penrose#53]
I like transparent status bars, so I made some changes to allow transparency which can be found [here](https://github.com/Danacus/penrose/tree/bar-transparency). 

Some pretty significant changes to `xcb_util` and the `draw` module are required to make it work.

I'm not sure if you are interested in adding this feature to penrose. If not I'll just keep it in my own fork and close this issue.

**Comment by sminez** [comment]
hey @Danacus , that looks really good! Do you have any screenshots of how this ends up looking? (/ how the config differs if at all)

So long as the changes you are proposing don't break the existing use of `StatusBar` this would be a great addition to have. My only comment would be that I'd prefer if the the `new_from_hex_rgb` and `new_from_hex_rgba` methods were combined (setting alpha to 1.0 if we just have rgb) so that users can always use a literal in functions that take a `impl Into<Color>`. I'm not sure if that's easier if the colors are `argb` as opposed to `rgba` but I always forget what the more common format is. Do you know?

**Comment by Danacus** [comment]
I will publish my personal penrose config somewhere soon, but here's a screenshot of the bar. 
![penrose](https://user-images.githubusercontent.com/7491613/92231188-a350f980-eeac-11ea-8b1a-e37f5ad91718.png)

Setting the background colors to a transparent color should be all that's needed.

I really wanted to keep `new_from_hex` as a single method, but I don't think there's a way to tell the difference between black (`0x000000`) and transparent (`0x00000000`), because they are both `0`. This is a bit unfortunate, but maybe you know a way around this?

I'm not sure whether `argb` or `rgba` is the more common format. I'm personally used to `rgba`. `rgba` is used in `OpenGL`, `PNG` and also on the web in `CSS`, so it seems pretty common to me.

Edit: You can find my config [here](https://gitlab.com/Danacus/penrose-config)

**Comment by sminez** [comment]
wouldn't black be `0x000000FF`? (with `0x00000000` being fully transparent the same way that `0x11111100` would be, no?)

Format wise, `rgba` is what I'm used to as well but I was having a weird feeling that the alpha channel was supposed to come first for some reason...not sure why now. `rgba` it is 👍

**Comment by Danacus** [comment]
Yes, black would be `0x000000FF`, but currently `0x000000` is also black, so it would break backwards compatibility. I'm not sure if that's a problem for you.

`cairo` also uses `rgba`, so using `rgba` makes even more sense when calling `set_source_rgba`.

**Comment by sminez** [comment]
aaaaaah...right, I understand what you mean now...in that case I'd be tempted to say that we always assume rgba not rgb when parsing from a `u32` given that we'll always have all four bytes. We can probably handle `rgb` values by adding a sanity check that if any of the top three bytes are non 0 but alpha is 0 then we probably want to set it to `FF`.

**Comment by Danacus** [comment]
I think I understand why `argb` would be easier. Let's say you have a hex in `rgb`: `0xRRGGBB` (RR, BB and GG are arbitrary values). In bytes it would be `[0, RR, GG, BB]`. Because there are non 0 bytes and alpha is 0, we could replace the first zero with `FF`. However, the same color in `rgba` would be `0xRRGGBBFF` which in bytes is `[RR, GG, BB, FF]`, not `[FF, RR, GG, BB]`. Everything is now shifted to the left except for the alpha value which is now on the right. We can probably find a way around this, but the point is that this would not have been a problem in the first place if we would have used `argb` instead. 

I think I can quiet easily get around this by using little endian bytes instead, so it shouldn't be a big deal. It does explain why you felt like the alpha channel was supposed to come first.

**Comment by Danacus** [comment]
The problem is a lot more complicated then I hoped it would be.

It can't tell the difference between `0xFFFFFF` (white, `rgb`) and `0x00FFFFFF` (light blue, `rgba`). I'm starting to think there's just no elegant way to detect whether an integer is `rgb` or `rgba`. I have however found a pretty neat way to convert them.

`rgba`:

```
let r = (hex >> 24 & 0xFF) as f64 / 255.0;
let g = (hex >> 16 & 0xFF) as f64 / 255.0;
let b = (hex >> 8 & 0xFF) as f64 / 255.0;
let a = (hex >> 0 & 0xFF) as f64 / 255.0;
```

`rgb`:

```
let r = (hex >> 16 & 0xFF) as f64 / 255.0;
let g = (hex >> 8 & 0xFF) as f64 / 255.0;
let b = (hex >> 0 & 0xFF) as f64 / 255.0;
let a = 1.0;
```

I'm afraid there might be no other option than to stick with either `rgb` or `rgba`. So we would have to choose between either using `rgba` and breaking backwards compatibility or using `rgb` and having to use strings or floats to define `rgba` colors. 

Alternatively we could use `argb` instead, like this:

```
let a = if hex > 0x00FFFFFF { (hex >> 24 & 0xFF) as f64 / 255.0 } else { 1.0 };
let r = (hex >> 16 & 0xFF) as f64 / 255.0;
let g = (hex >> 8 & 0xFF) as f64 / 255.0;
let b = (hex >> 0 & 0xFF) as f64 / 255.0;
```

We can now detect non-zero alpha values simply by checking if the hex is greater than `0x00FFFFFF`. This works fine except for one thing: you can't create a completely transparent color this way, because `0x0` is `0x0` regardless of how many zeros you add.
Adding an exception to make `0x0` transparent removes the ability to create black, so that's not ideal either.

Which solution do you think is best?

I have pushed the changes to my branch, which also include some new unit tests.

**Comment by sminez** [comment]
Hmm..I think it's probably best to just go for `rgba` then: there aren't all that many people using penrose to be honest so it's not a huge problem to break backward compatability (particularly in this relatively minor way). This is why I have the disclaimer in the REACME afterall :wink: 

As for the conversion function, I'd prefer to keep the stdlib method on `u32` if that's ok. I used the same bitshifting trick you've proposed originally but I felt that the stdlib version was cleaner in the end :slightly_smiling_face:
