### ISSUE TITLE
exposing the ring rotate feature at the manager level

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#59]
**Is your feature request related to a problem? Please describe.**
At present the bility to rotate the stack is present in the Ring data type but it is not present at a level where it can be used for binding to a key. 

This would be useful in implementing window movements like rotating windows through the master area with a single key press.

**Describe the solution you'd like**
I would like to have a simple function that takes a direction allowing for the windows of the stack to be rotated without moving the the focus from the pane that currently has iit

**Describe alternatives you've considered**

I have looked at doing this with varios window shuffling methods but they would be messy especially since the functionality already exists to do this cleanly.

**Additional context**

**Comment by sminez** [comment]
This is already exposed at the workspace level.

**Comment by sminez** [comment]
Ah, hang on. Sorry, that should already be exposed but you are completely correct: it's not actually available in the public api
