### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by ghost** [sminez/penrose#6]
The way penrose works right now, `run_external!()` will produce zombie processes. In order to avoid that, one can install a signal handler function or simply configure `SIGCHLD` to be ignored. For instance, adding this after the `WindowManager::init()` call is sufficient:

```
unsafe { signal::signal(Signal::SIGCHLD, SigHandler::SigIgn) }.unwrap();
```

Tested with penrose 0.1.5 and nix 0.17.0

Alternatively, `run_external!()` could wait for process completion, but I don't think that would fit into the overall design.

**Comment by sminez** [comment]
Ah! Thanks for spotting that! Just had another look at the docs and realised that this is covered when talking about **std::process::Child**  but not mentioned in the docs for **spawn** which is a little annoying. You're right that waiting for process completion doesn't fit the current design (I tinkered with it previously) so I suspect that configuring SIGCHILD to be ignored might be the way to go.
