### ISSUE TITLE
focus bouncing when playiing video in monocle mode

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#60]
**Describe the bug**
when playing a video using mpv in monocle mode the focus will bounce between the video and the other window. This may be related to #52

If the mouse pointer is moved to the status bar this stops

**To Reproduce**
switch to monocle layout
open a terminal
run mpv -vo xv video,mp4
switch to another workspace and back

**Desktop (please complete the following information):**
 - OS: linux
 - Distribution debian
 - Version sid

**Comment by sminez** [comment]
@crypt17 as requested in #47 when you raised an issue previously, please can you fill in all of the bug template including providing a minimal main.rs that reproduces the bug. The [minimal](https://github.com/sminez/penrose/blob/develop/examples/minimal/main.rs) example in the `examples` directory is a good starting point for this.

In particular: I need to know if this is related to `mpv` specifically (I assume this issue does not happen for other programs given that you are mentioning it but I have no way of knowing). I also need to know if this only happens on the `monocle` layout, and if so how you have configured that layout. Does this only happen when you toggle between workspaces?

As stated in the README of this repo: this is a hobby project. I don't have time or capacity to try and work this sort of thing out from the the level of detail you are providing when raising bugs. Sorry.

**Comment by crypt17** [comment]
Hi I have so far worked out that this is an interaction of
    wm.set_client_insert_point(InsertPoint::AfterFocused);

which I have after

    let mut wm = WindowManager::init(config, &conn);

I am not yet sure what it is that it is interacting with but I am working
on tracking this down but I have run out of time at the moment.

I have seen the effect in a number of thing not just mpv I just listed mpv
as it was an easy example.

**Comment by sminez** [comment]
@crypt17 I am closing this for now as the details provided so far indicate that this is a configuration issue specific to your use of `penrose` as a crate. If you manage to narrow things down and can provide full details in the future, please feel free to open a new issue using the issue template.

**Comment by crypt17** [comment]
I am currently thinking that it may be an issue with the focus variable
that is cached in manager getting out if sync with the value at the
workspace level but I have not found evidence of this yet. This could
explain why it shows up with monocle and paper and not the other layout
which ignore focus

I will send through more info when I have had timn to look further at this .
