### ISSUE TITLE
looking for info

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#63]
Is there an easy way to get the index position of a window given a window id

I am writing a hook to adjust the focsed window when the current window is closed and I need the position of the window in the stack to deal with the corner case where the window is the last window in the stack.

**Comment by sminez** [comment]
Not as a built in method no. You should be able to check your edge case by using the existing methods on **WindowManager** to determine the number of clients on the current workspace and then checking the id of the last client by index so you can compare to the id of the client you care about.

**Comment by crypt17** [comment]
that was the conclusion that I came to on a bike ride.
