### ISSUE TITLE
possible error in cycle workspace

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#64]
**Describe the bug**
when usinng a combination of focus_workspace ans cycle_workspace cycle_workspace can use the previous workspace as its starting index rather than the current one.

**To Reproduce**
start at workspace 3 
switch to workspace 1 using M-1
move to workspace 2 using cycle_worspace M-period

you end up at workspace 4 rather than workspace 1

**Expected behavior**
cycle_workspace should take you to the next workspace from the current one
ie starting at workspace 1 cycle_workspacce(Forward) should take you to workspace 2

**Desktop (please complete the following information):**
 - OS: linux
 - Distribution debian
 - Version sid

**Additional context**
- [ ] minimal main.rs
/**
 * penrose :: minimal configuration
 * This file will give you a functional if incredibly minimal window manager that has multiple
 * workspaces and simple client/workspace movement. For a more fleshed out example see the
 * 'simple_config_with_hooks' example.
 */
#[macro_use]
extern crate penrose;

use penrose::{Backward, Config, Forward, Less, More, WindowManager, XcbConnection};

fn main() {
    let config = Config::default();
    let key_bindings = gen_keybindings! {
        "M-j" => run_internal!(cycle_client, Forward),
        "M-k" => run_internal!(cycle_client, Backward),
        "M-S-j" => run_internal!(drag_client, Forward),
        "M-S-k" => run_internal!(drag_client, Backward),
        "M-S-q" => run_internal!(kill_client),
        "M-Tab" => run_internal!(toggle_workspace),
        "M-bracketright" => run_internal!(cycle_screen, Forward),
        "M-bracketleft" => run_internal!(cycle_screen, Backward),
        "M-S-bracketright" => run_internal!(drag_workspace, Forward),
        "M-S-bracketleft" => run_internal!(drag_workspace, Backward),
        "M-grave" => run_internal!(cycle_layout, Forward),
        "M-S-grave" => run_internal!(cycle_layout, Backward),
        "M-A-Up" => run_internal!(update_max_main, More),
        "M-A-Down" => run_internal!(update_max_main, Less),
        "M-A-Right" => run_internal!(update_main_ratio, More),
        "M-A-Left" => run_internal!(update_main_ratio, Less),
        "M-A-Escape" => run_internal!(exit),
        "M-semicolon" => run_external!("dmenu_run"),
        "M-Return" => run_external!("st"),
      // bindings for cycle_workspace
        "M-period" => run_internal!(cycle_workspace, Forward),
        "M-comma"  => run_internal!(cycle_workspace, Backward);

        forall_workspaces: config.workspaces => {
            "M-{}" => focus_workspace,
            "M-S-{}" => client_to_workspace,
        }
    };

    let conn = XcbConnection::new().unwrap();
    let mut wm = WindowManager::init(config, &conn);
    wm.grab_keys_and_run(key_bindings);
}

**Comment by sminez** [comment]
Looks like this was an issue with `focus_workspace` not setting the focused element on the underlying datastructure that handles workspaces. The only thing looking at that was `cycle_workspaces` which is why it only shows up when the two interact. The fix is now on the develop branch.

**Comment by crypt17** [comment]
many thanks I will have a play with this tomorrow.
