### ISSUE TITLE
Resize client

### ISSUE THREAD

**Issue by sminez** [sminez/penrose#66]
Floating windows are currently restricted to being the size that they were upon initial creation of when they were set to floating. It would be useful to be able to alter the size of floating windows

### Describe the change / addition you'd like to see made

It should be possible to set the current size of a client through predefined increments (inc left/right/up/down by n pixels for example).

### AC

- [x] A new position can be set absolutely (the `float` method on `StackSet` handles this)
- [x] Changes can be made to an existing floating window position through a custom action

**Comment by Aleod-m** [comment]
From what i understood what is needed to be implement are the following functions  on the `Workspace` struct : 
```rust
pub fn resize_floating_client(&mut self, id : WinId, corner : Point) -> ResizeAction;
pub fn grow_floating_client(&mut self, id : WinId, dir : RelativePosition, change : Change) -> ResizeAction;
```
Am i right ?
(Ofc its not all there is to do but it is the starting point)

**Comment by sminez** [comment]
No actually: the methods need to be on the window manager not the workspace struct, and the main bulk of the work is in handling the mouse events from the X server.

I'm in the middle of trying to sort out some issues around event handling and window focus currently so work on this issue can't start until that is complete.

**Comment by sminez** [comment]
This is now available for use (along with other related actions for floating clients) here: https://github.com/sminez/penrose/blob/develop/src/builtin/actions/floating.rs
