### ISSUE TITLE
InsertPosition::Index() documentation is incorrect

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#69]
Describe the bug
when used as documented InsertPosition::Indexgices a bounds error

The documentation for this says that it will add to the end of the list if out of bounds but this check is not done so it will crash on the first window being opened if it is set to anything other than 0 making it non functional.

Additional context

- debug log output

**Comment by sminez** [comment]
https://github.com/sminez/penrose/blob/9cd9f2433afacdab7f11306e6592229d232f42e2/src/core/ring.rs#L491

You are right that if am out of bounds index is given but only for out of bounds, not anything other than index 0. https://github.com/sminez/penrose/blob/9cd9f2433afacdab7f11306e6592229d232f42e2/src/core/ring.rs#L491

I'll adjust the doc comment to reflect this as the current behaviour is consistent with `insert` behaviour for standard library collections. Please make sure you are generating the indices you are using correctly.
