### ISSUE TITLE
Dialog windows don't float by default

### ISSUE THREAD

**Issue by yohannd1** [sminez/penrose#78]
### Is your feature request related to a problem? Please describe

Yes - I've noticed some (or maybe all) dialog windows, when opened on penrose, don't float by default. One example for this is the "choose file to upload" dialog from discord, which in my machine is a GtkFileChooser type window.

### Describe the change / addition you'd like to see made

It would be good to mark some windows with dialog attributes as floating by default, or at least make it easier to do so via hooks.

### Describe alternatives you've considered

I've considered making a hook for simulating this behavior but I don't think it would work as well since there doesn't seem to be a way to get attributes like the `_NET_WM_WINDOW_TYPE` field that can be seen by running `xprop` on some windows.

### Additional context

For the Discord file chooser window, the `xprop` output I got was:

```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
_NET_WM_USER_TIME(CARDINAL) = 11131761
_NET_WM_DESKTOP(CARDINAL) = 0
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
                window id # of group leader: 0x1a00001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 543, 371
WM_WINDOW_ROLE(STRING) = "GtkFileChooserDialog"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 27263005, 27263006
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1a0001c
WM_CLIENT_LEADER(WINDOW): window id # 0x1a00001
_NET_WM_PID(CARDINAL) = 3857332
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "core"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified minimum size: 593 by 326
                program specified base size: 0 by 0
                window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "discord", "Discord"
WM_ICON_NAME(STRING) =
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) =
```

I wonder if the only way most tiling window managers decide if a window should float by default is by the `_NET_WM_WINDOW_TYPE_DIALOG` flag or if things like a maximum size specified on `WM_NORMAL_HINTS(WM_SIZE_HINTS)` (which this window doesn't have) should affect it too.

**Comment by sminez** [comment]
There is a [floating_classes](https://github.com/sminez/penrose/blob/588c7771a31681d215e551859b84be9f0a4d08bd/src/core/manager.rs#L39) config option for the `WindowManager` that should handle this if you set the relevant classes. There is also a list of [auto-float](https://github.com/sminez/penrose/blob/588c7771a31681d215e551859b84be9f0a4d08bd/src/core/xconnection.rs#L151) classes that _should_ work if the clients in question are setting the correct WM class. The Discord example you give seems to be setting `_NET_WM_WINDOW_TYPE_DIALOG` which _should_ work...I'll take a look.

**Comment by sminez** [comment]
Sorry for the delay in getting back to you on this on @YohananDiamond, the fix is now on develop as of https://github.com/sminez/penrose/commit/3676976b66f24cfb81acb6b456731a68ab4d0b51 and I will be cutting a new release of `penrose` soon to include it.

**Comment by yohannd1** [comment]
Thanks, it's working well now! And no need to worry about the delay ^^.
