### ISSUE TITLE
Polybar thinks all workspaces are empty

### ISSUE THREAD

**Issue by yohannd1** [sminez/penrose#79]
### Describe the bug

Polybar doesn't seem to understand if a workspace is empty, and ends up marking all workspaces as empty.

### To Reproduce

1. Configure polybar to have the following module:
```
[module/ewmh]
type = internal/xworkspaces

format = <label-state>

label-active = " %index% "
label-occupied = " %index% "
label-urgent = " %index% "
label-empty = " %index% [E] "
```
2. Open penrose and polybar
3. Open a window
4. Switch to another workspace (because `label-active` overrides `label-empty`)
5. The (now inactive/unfocused) workspace with a window is still marked as [E]

### Expected behavior

The workspace should not be with the [E] flag anymore.

### Screenshots

Focusing workspace 4, with a terminal window:

![image](https://user-images.githubusercontent.com/23298480/99198639-b7e92200-2778-11eb-8e9c-c6219a745796.png)

Switched to workspace 5, workspace 4 is still with the terminal window and should not be marked as [E] (there's still the `yohanan@core:~` text there which would be the terminal window's title, but it's not because it didn't update - still investigating this):

![image](https://user-images.githubusercontent.com/23298480/99198673-eb2bb100-2778-11eb-9493-d725418923e7.png)

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- OS Version: 5.9.8-arch1-1
- Penrose Version (from `Cargo.lock`): `0.1.11` (`git+https://github.com/sminez/penrose?branch=develop#588c7771a31681d215e551859b84be9f0a4d08bd`)
- Polybar Version: `3.4.0-115-g2f4cffc0 +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard`

### Additional context

It might be possible that this is a problem in polybar instead of penrose but I believe that the feature simply isn't implemented on penrose (description says *partial EWMH support*). I am not sure on how to help on this one but if I find any extra useful information I'll post it here.

**Comment by sminez** [comment]
Hi @YohananDiamond :wave: 

I tried to get this working in the past using EWMH properties on the client but nothing I did seemed to work... If you have any examples of window managers doing this correctly please do let me know! Since implementing the built in status bar I'm afraid I've not focused much on support for things like polybar as I don't have the time to dedicate to it if it's not going to be part of my own use of penrose. Happy to accept a PR that addresses this or to take a look at it further if there is a clear path forward :slightly_smiling_face:

**Comment by yohannd1** [comment]
Okay! If I do find some information I'll post about it here and try to make a PR on it.

But to be honest, I think I should be using the built in status bar too ^^'.

**Comment by yohannd1** [comment]
By peeking at polybar's source code, I found [this](https://github.com/polybar/polybar/blob/1c554dd0e030291bb71d617f0006219901e0bbcc/src/modules/xworkspaces.cpp#L235-L261):
```
/**
 * Update active state of current desktops
 */
void xworkspaces_module::rebuild_desktop_states() {
  std::set<unsigned int> occupied_desks;
  for (auto&& c : m_clients) {
    occupied_desks.insert(c.second);
  }

  for (auto&& v : m_viewports) {
    for (auto&& d : v->desktops) {
      if (d->index == m_current_desktop) {
        d->state = desktop_state::ACTIVE;
      } else if (occupied_desks.count(d->index) > 0) {
        d->state = desktop_state::OCCUPIED;
      } else {
        d->state = desktop_state::EMPTY;
      }

      d->label = m_labels.at(d->state)->clone();
      d->label->reset_tokens();
      d->label->replace_token("%index%", to_string(d->index + 1));
      d->label->replace_token("%name%", m_desktop_names[d->index]);
      d->label->replace_token("%icon%", m_icons->get(m_desktop_names[d->index], DEFAULT_ICON)->get());
    }
  }
}
```
It seems like polybar marks a desktop as empty (`desktop_state::EMPTY`, which is an enum value) by manually counting which workspaces have more than 0 clients.
```
std::set<unsigned int> occupied_desks;
for (auto&& c : m_clients) {
  occupied_desks.insert(c.second);
}
```
I also looked through the definition of the `m_clients` variable and noticed it has the [following signature](https://github.com/polybar/polybar/blob/1c554dd0e030291bb71d617f0006219901e0bbcc/include/modules/xworkspaces.hpp#L97-L100):
```
/**
 * Maps an xcb window to its desktop number
 */
map<xcb_window_t, unsigned int> m_clients;
```
I suspect that somehow polybar is not being able to infer on which workspace each client is.

Then I found [this bit of code](https://github.com/polybar/polybar/blob/1c554dd0e030291bb71d617f0006219901e0bbcc/src/modules/xworkspaces.cpp#L147-L150), which seems to be the one that manages `m_clients`, and it refers to a [`ewmh_util::get_desktop_from_window`](https://github.com/polybar/polybar/blob/1c554dd0e030291bb71d617f0006219901e0bbcc/src/x11/ewmh.cpp#L122-L127) function:

```
unsigned int get_desktop_from_window(xcb_window_t window) {
  auto conn = initialize().get();
  unsigned int desktop = XCB_NONE;
  xcb_ewmh_get_wm_desktop_reply(conn, xcb_ewmh_get_wm_desktop(conn, window), &desktop, nullptr);
  return desktop;
}
```

I believe this reply that is requested by `xcb_ewmh_get_wm_desktop_reply` might be what is failing.
Will update soon on more information (I need to look up how `xcb_ewmh_get_wm_desktop_reply` and `xcb_ewmh_get_wm_desktop` work but I can't right now).

**Comment by yohannd1** [comment]
Hm. I'm struggling to find any info at all on this. Weird.

**Comment by sminez** [comment]
I've had a look again and I'm pretty sure that I _am_ following the same logic as used by [awesome](https://github.com/awesomeWM/awesome/blob/e0bb29962d3d68613f4c9879e4a7f7ee5e65518b/ewmh.c#L524). The following (run from inside penrose on Firefox) also seems to show that the property _is_ being set correctly :confused: 
```bash
$ xprop | grep DESKTOP 
_NET_WM_DESKTOP(CARDINAL) = 2
```

**Comment by sminez** [comment]
Looking at polybar again, I think this is going to be down to this: https://www.github.com/polybar/polybar/tree/1c554dd0e030291bb71d617f0006219901e0bbcc/src%2Fmodules%2Fxworkspaces.cpp (on line 146 in particular).

Penrose doesn't currently set the client list at all so while all the clients report their desktop, polybar can't find them... I'll be honest, I thought it would be finding the list of clients from the X server directly :facepalm:

This shouldn't be too hard to fix if this is all it is, but I think I'll take a look at what other properties need setting and try to make sure that they are all done now rather than leaving them unimplemented.

**Comment by sminez** [comment]
The above commit addresses the issue of penrose not setting the `_NET_WM_CLIENT_LIST` property but in my testing that still doesn't seem to resolve the issue with polybar not being able to see which desktops now contain clients :confused: 

@YohananDiamond are you able to try with your set up? There's a chance my config for polybar is wrong I suppose :shrug: 
If you could also run `xprop -root` when running another window manager where polybar _does_ behave correctly that would be really helpful. For reference, this is what `penrose` now gives:
```bash
$ xprop -root
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x200005
_NET_CLIENT_LIST(ATOM_WINDOW) = 
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", "6", "7", "8", "9"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 9
_NET_SUPPORTED(ATOM) = _NET_ACTIVE_WINDOW, _NET_CLIENT_LIST, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_NUMBER_OF_DESKTOPS, _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_STATE, _NET_WM_STATE_FULLSCREEN, _NET_WM_WINDOW_TYPE
_NET_WM_NAME(UTF8_STRING) = "penrose"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x600000
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
```

**Comment by yohannd1** [comment]
Hello! Sorry for not responding on the past week. I somehow didn't receive the notification and ended up not reading it until earlier today ^^'

I've tried your new commit and sadly it indeed didn't work. I also tried polybar on bspwm and it worked there; here's the output of `xprop -root`:

```
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x600006, 0x1200006, 0x1400006, 0xa00006
_NET_ACTIVE_WINDOW(WINDOW): window id # 0xa00006
_NET_CLIENT_LIST(WINDOW): window id # 0x600006, 0x1200006, 0x1400006, 0xa00006
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x800001
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x800001
GDK_VISUALS(INTEGER) = 306, 405
_NET_CURRENT_DESKTOP(CARDINAL) = 1
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 2
XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 13, -82, -37, 21, 0, 0, 0, 0, 18, 26, 1, 4, -107, 34, 19, 120, 2, -61, -59, -111, 85, 84, -108, 40, 36, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -38, 29, 86, -30, 80, 0, 32, 48, 68, 45, 71, 0, 88, -63, 16, 0, 0, 26, -30, 23, 86, -30, 80, 0, 32, 48, 68, 45, 71, 0, 88, -63, 16, 0, 0, 26, 0, 0, 0, -2, 0, 74, 77, 67, 57, 88, -128, 49, 53, 54, 66, 71, 65, 10, 0, 0, 0, 0, 0, 0, 65, 49, -106, 0, 16, 0, 0, 9, 1, 10, 32, 32, 0, 53
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0xc00000
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_DESKTOP_NAMES, _NET_DESKTOP_VIEWPORT, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_CLIENT_LIST, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_WM_STRUT_PARTIAL, _NET_WM_DESKTOP, _NET_WM_STATE, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_BELOW, _NET_WM_STATE_ABOVE, _NET_WM_STATE_STICKY, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_TOOLBAR
RESOURCE_MANAGER(STRING) = "st.alpha:\t0.9\nst.cursor:\t#83a598\nst.font:\tIosevkaMedium:pixelsize=13.5:antialias=true:autohint=true;\ndwm.norm.bg:\t#282828\ndwm.norm.fg:\t#d5c4a1\ndwm.norm.border:\t#282828\ndwm.sel.bg:\t#504945\ndwm.sel.fg:\t#d5c4a1\ndwm.sel.border:\t#665c54\ndwm.font:\tIosevkaMedium:pixelsize=13.5:antialias=true:autohint=true;\ndmenu.font:\tIosevkaMedium:pixelsize=13.5:antialias=true:autohint=true;\ndmenu.norm.bg:\t#282828\ndmenu.norm.fg:\t#d5c4a1\ndmenu.norm.hl.bg:\t#282828\ndmenu.norm.hl.fg:\t#fe8019\ndmenu.sel.bg:\t#504945\ndmenu.sel.fg:\t#d5c4a1\ndmenu.sel.hl.bg:\t#504945\ndmenu.sel.hl.fg:\t#fe8019\ndmenu.out.bg:\t#d65d0e\ndmenu.out.fg:\t#d65d0e\nqutebrowser.fontname:\tIosevkaMedium\nqutebrowser.font_size:\t11pt\nqutebrowser.bg:\t#282828\nqutebrowser.fg:\t#d5c4a1\nqutebrowser.bg-alt:\t#3c3836\nqutebrowser.fg-alt:\t#bdae93\nqutebrowser.bg-attention:\t#3c3836\nqutebrowser.fg-attention:\t#bdae93\nqutebrowser.sel.bg:\t#504945\nqutebrowser.sel.fg:\t#d5c4a1\nqutebrowser.match.fg:\t#fe8019\nqutebrowser.error:\t#fb4934\nqutebrowser.warning:\t#fe8019\nqutebrowser.info:\t#83a598\nqutebrowser.success:\t#b8bb26\nEmacs.font:\tIosevkaMedium\npenrose.highlight:\t#665c54\npolybar.fontname:\tIosevkaMedium\npolybar.fontsize:\t9.5\n*background:\t#282828\n*foreground:\t#d5c4a1\n*bg:\t#282828\n*fg:\t#d5c4a1\n*cursor:\t#83a598\n*cursorColor:\t#83a598\n*.color0:\t#282828\n*.base00:\t#282828\n*.color1:\t#3c3836\n*.base01:\t#3c3836\n*.color2:\t#504945\n*.base02:\t#504945\n*.color3:\t#665c54\n*.base03:\t#665c54\n*.color4:\t#bdae93\n*.base04:\t#bdae93\n*.color5:\t#d5c4a1\n*.base05:\t#d5c4a1\n*.color6:\t#ebdbb2\n*.base06:\t#ebdbb2\n*.color7:\t#fbf1c7\n*.base07:\t#fbf1c7\n*.color8:\t#fb4934\n*.base08:\t#fb4934\n*.color9:\t#fe8019\n*.base09:\t#fe8019\n*.color10:\t#fabd2f\n*.color11:\t#b8bb26\n*.color12:\t#8ec07c\n*.color13:\t#83a598\n*.color14:\t#d3869b\n*.color15:\t#d65d0e\n*.base0A:\t#fabd2f\n*.base0B:\t#b8bb26\n*.base0C:\t#8ec07c\n*.base0D:\t#83a598\n*.base0E:\t#d3869b\n*.base0F:\t#d65d0e\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "br", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 2
```

Also, sorry for the large `RESOURCE_MANAGER`; I use X resources a lot :P

By the way, I did only have 2 desktops on this setup - that might confuse a little bit.

**Comment by yohannd1** [comment]
I've noticed one thing: on this latest commit, apparently the `_NET_CLIENT_LIST` is sometimes provided empty, even when there are clients, but I'm not sure when. It seems like it's not being updated every time it needs to (which I believe would be when a new window is created, deleted, or moved between workspaces.

Looking through the code of your commit, the deletion part is there, but since I don't know much on the topic I'm not sure if the `handle_map_request` can be responsible for both new windows and window changes, but as far as I can see it's the other location where the call to update the client list was.

**Comment by yohannd1** [comment]
Update! For some reason this issue is not present anymore for me as of [`d9ab92f17de6...`](https://github.com/sminez/penrose?branch=develop#d9ab92f17de6aa7559b9259c88a74e12ff385bd9).
I don't know exactly why it started working out of the blue, but that's very nice :P

I'll be closing this issue for now. If I find any issue again I'll post about it here.

**Comment by sminez** [comment]
Oh! Huh...well that's good I suppose 😄
