### ISSUE TITLE
Sometimes, StatusBar is not recreated immediately on resolution change

### ISSUE THREAD

**Issue by NeoDarkFire** [sminez/penrose#88]
### Describe the bug

When the screen resolution changes, the status bar is destroyed and should always be recreated right away with the new resolution. However, it is now only shown again when doing something like switching workspace and focusing another client (possibly destroying a client too).

This also affects status bars of other screens.

### To Reproduce

1. Change the screen resolution (for example `xrandr --output eDP-1-1 --mode 640x480`).
2. The status bar is gone.
3. Change workspace.
4. The bar is there again.

### Expected behavior

The status bar should be displayed immediately.

### Versions & OS Details

- OS: Linux
- Distribution: Arch
- OS Version: 5.9.14-arch1-1
- Penrose Version: `cfec14bf6a560b2def7914a16d17a0b07356f071`

**Comment by sminez** [comment]
I'm not sure _how_ but this feels like the initial mapping of the newly recreated status bar instances is being not happening for some reason. I have no idea why that would be the case though as the window should be being created and mapped immediately, with the connection being flushed straight after: https://github.com/sminez/penrose/blob/6976670000fb30f59ffe748cdb87727b068d3b7e/src/core/helpers.rs#L247

**Comment by sminez** [comment]
@NeoDarkFire as of the above commit I think this is working for me now? Need to double check in the morning with an external monitor but using xrandr to modify the screen resolution now immediately recreates the bar for me.

**Comment by NeoDarkFire** [comment]
I can confirm this works for one screen :smile: 

However, when I try starting penrose with a second screen to test, it crashes immediately. The only line in the log file is "Error: Screen index out of bounds" (even without executing xrandr commands on startup with a script).
I tried finding a reference to this error message in the code and found none.
When I try with my second screen after penrose already started, the status bar is rendered only on the first screen.

Finally, with the commit referenced above (`8d2d79a`) ~~it always renders properly~~ (although on one screen), but with the latest commit it's completely black (but xprop works on it).

Edit: I unplugged my second screen after writing this and I now realize the status bar does not render properly and is in fact frozen.

**Comment by sminez** [comment]
@NeoDarkFire  I've verified this working on startup for me with mutliple monitors now. Looks like a 'bug' I fixed while trying to look into another issue you raised around bars only working for the first monitor was the cause of this crash. There is better error handling / logging in place now so you should see a more helpful error message if you hit something like this in the future.

If there are other issues related to this, please raise them in their own bug report here in GitHub so I can track each one separately
