### ISSUE TITLE
Keep focused workspace on screen resolution changes

### ISSUE THREAD

**Issue by NeoDarkFire** [sminez/penrose#89]
### Is your feature request related to a problem? Please describe

When the screen resolution changes, the currently focused workspace changes back to the first.

### Describe the change / addition you'd like to see made

It would be great to keep the currently focused workspace. For example if I switch to workspace 3 and the screen resolution changes (for exemple by launching a game), I'd like to still be in workspace 3.

**Comment by sminez** [comment]
Implemented in #95
