### ISSUE TITLE
Reparented zombies

### ISSUE THREAD

**Issue by ghost** [sminez/penrose#9]
#6 has mostly been resolved, but it's still possible to get zombies. Here's how: a common way to start window managers is to exec it as the last command in `~/.xinitrc`. If any background process you spawned before exec hasn't finished, then it will be adopted by penrose as a zombie since penrose is unaware of its existence and doesn't configure relevant signal handling (as suggested in #6).

```
xmodmap
set-wallpaper&
exec penrose
```

In this example, `set-wallpaper` can turn into a penrose zombie.

**Comment by sminez** [comment]
Hi @tuncer 👋 
You provided some additional information about this (including how other WMs handle this issue) when you contacted me earlier. Are you able to add that to the issue?

**Comment by ghost** [comment]
hadlock, spectrwm and dwm:
- https://github.com/AdaShoelace/hadlock/blob/master/src/main.rs#L36
- https://github.com/conformal/spectrwm/blob/master/spectrwm.c#L2184
- https://git.suckless.org/dwm/file/dwm.c.html#l1633

Also see:
- https://iximiuz.com/en/posts/dealing-with-processes-termination-in-Linux/
- https://www.fpcomplete.com/rust/pid1/

**Comment by sminez** [comment]
@tuncer I've reverted the changes made for #6 in favour of your original suggestion (see 1cf40b58c7e968c48fd30bcbf7068264c51e04fd )

I've tested it out and everything seems to work as expected, are you able to confirm? I've set the handler up inside of **grab_keys_and_run** as this is where penrose takes over program execution. The idea being that as more optional functionality is added, you can initialise the WindowManager and then add hooks / extensions  before dropping in to the event loop. With that in mind, it doesn't feel quite right to configure the handler in **init** but I may be wrong.

**Comment by ghost** [comment]
Thanks, works here as well.
